<?php

	//
	// Project Management DBSM-independent queries
	//

	//
	// Customers queries
	//

	$qr_pm_select_customer = "SELECT * FROM CUSTOMER WHERE C_ID='!C_ID!'";

	$qr_pm_add_customer = "INSERT INTO CUSTOMER(C_ID, C_NAME, C_ADDRESSSTREET, C_ADDRESSCITY, C_ADDRESSSTATE, 		C_ADDRESSZIP, C_ADDRESSCOUNTRY, C_CONTACTPERSON, C_PHONE, C_FAX, C_STATUS, C_EMAIL, C_MODIFYDATETIME, C_MODIFYUSERNAME) VALUES ('!C_ID!', '!C_NAME!', '!C_ADDRESSSTREET!', '!C_ADDRESSCITY!', '!C_ADDRESSSTATE!', '!C_ADDRESSZIP!', '!C_ADDRESSCOUNTRY!', 	'!C_CONTACTPERSON!', '!C_PHONE!', '!C_FAX!', '!C_STATUS!', '!C_EMAIL!', '!C_MODIFYDATETIME!', '!C_MODIFYUSERNAME!')";

	$qr_pm_modify_customer = "UPDATE CUSTOMER SET C_NAME='!C_NAME!', C_ADDRESSSTREET='!C_ADDRESSSTREET!', 	C_ADDRESSCITY='!C_ADDRESSCITY!', C_ADDRESSSTATE='!C_ADDRESSSTATE!', C_ADDRESSZIP='!C_ADDRESSZIP!', C_ADDRESSCOUNTRY='!C_ADDRESSCOUNTRY!', C_CONTACTPERSON='!C_CONTACTPERSON!', C_PHONE='!C_PHONE!', C_FAX='!C_FAX!', 	C_EMAIL='!C_EMAIL!', C_MODIFYDATETIME='!C_MODIFYDATETIME!', C_MODIFYUSERNAME='!C_MODIFYUSERNAME!' WHERE C_ID='!C_ID!'";

	$qr_pm_select_customer_status = "SELECT C_STATUS FROM CUSTOMER WHERE C_ID = '!C_ID!'";

	$qr_pm_delete_customer = "UPDATE CUSTOMER SET C_STATUS=1, C_MODIFYDATETIME='!C_MODIFYDATETIME!', C_MODIFYUSERNAME='!C_MODIFYUSERNAME!' WHERE C_ID='!C_ID!'";

	$qr_pm_select_customer_list = "SELECT * FROM CUSTOMER WHERE C_STATUS='%s' ORDER BY %s";

	$qr_pm_count_customer_active_projects = "SELECT COUNT(*) FROM PROJECT WHERE (P_ENDDATE > NOW() OR P_ENDDATE IS NULL) AND C_ID='!C_ID!'";

	$qr_pm_count_customer_projects = "SELECT COUNT(*) FROM PROJECT WHERE C_ID='!C_ID!'";

	$qr_pm_select_customer_projects = "SELECT P_ID FROM PROJECT WHERE C_ID='!C_ID!'";

	$qr_pm_restore_customer = "UPDATE CUSTOMER SET C_STATUS=0, C_MODIFYDATETIME='!C_MODIFYDATETIME!', C_MODIFYUSERNAME='!C_MODIFYUSERNAME!' WHERE C_ID='!C_ID!'";

	$qr_pm_delete_customer_permanently = "DELETE FROM CUSTOMER WHERE C_ID='!C_ID!'";

	$qr_pm_count_customers = "SELECT COUNT(C_ID) FROM CUSTOMER WHERE C_STATUS='%s'";

	//
	// Project queries
	//

	$qr_pm_add_project = "INSERT INTO PROJECT(P_ID, C_ID, P_DESC, P_BILLABLE, P_STARTDATE, U_ID_MANAGER, P_MODIFYDATETIME, P_MODIFYUSERNAME) VALUES ('!P_ID!', '!C_ID!', '!P_DESC!', '!P_BILLABLE!', '!P_STARTDATE!', '!U_ID_MANAGER!', '!P_MODIFYDATETIME!', '!P_MODIFYUSERNAME!')";
	
	$qr_pm_modify_project = "UPDATE PROJECT SET C_ID='!C_ID!', P_DESC='!P_DESC!', P_BILLABLE='!P_BILLABLE!', U_ID_MANAGER='!U_ID_MANAGER!', P_MODIFYDATETIME='!P_MODIFYDATETIME!', P_MODIFYUSERNAME='!P_MODIFYUSERNAME!', P_STARTDATE='!P_STARTDATE!' WHERE P_ID='!P_ID!'";

	$qr_pm_select_project = "SELECT P.*, C.C_NAME, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME, CA.C_EMAILADDRESS FROM PROJECT P, CUSTOMER C, WBS_USER U, CONTACT CA WHERE CA.C_ID=U.C_ID AND P.P_ID = '!P_ID!' AND C.C_ID = P.C_ID AND U.U_ID = P.U_ID_MANAGER";

	$qr_pm_select_active_projects = "SELECT P.*, C.C_NAME, CN.* FROM PROJECT P, CUSTOMER C, WBS_USER U, CONTACT CN WHERE P.C_ID = C.C_ID AND ( P.P_ENDDATE IS NULL OR P.P_ENDDATE > NOW() ) AND P.U_ID_MANAGER = U.U_ID AND C.C_STATUS = 0 AND CN.C_ID=U.C_ID ORDER BY %s, P.P_DESC";

	$qr_pm_select_projects_ordered = "SELECT P.P_ID, P.P_DESC, P.P_ENDDATE, C.C_NAME, (P_ENDDATE <> '' and P_ENDDATE <= CURDATE()) as CLOSED FROM PROJECT P, CUSTOMER C WHERE P.C_ID = C.C_ID AND C.C_STATUS = 0 ORDER BY (P_ENDDATE <> '' and P_ENDDATE <= CURDATE()), C.C_NAME, P.P_DESC";

	$qr_pm_select_projects = "SELECT P.*, C.C_NAME, CN.* FROM PROJECT P, CUSTOMER C, WBS_USER U, CONTACT CN WHERE P.C_ID = C.C_ID AND P.U_ID_MANAGER = U.U_ID AND CN.C_ID=U.C_ID ORDER BY %s, P.P_DESC";
	
	$qr_pm_select_closed_projects = "SELECT P.*, C.C_NAME, CN.* FROM PROJECT P, CUSTOMER C, WBS_USER U, CONTACT CN WHERE P.C_ID = C.C_ID AND ( P.P_ENDDATE IS NOT NULL AND P.P_ENDDATE <= NOW() ) AND P.U_ID_MANAGER = U.U_ID AND CN.C_ID=U.C_ID ORDER BY %s, P.P_DESC";

	$qr_pm_select_active_projects_limited = "SELECT P.*, C.C_NAME FROM PROJECT P, CUSTOMER C, WBS_USER U WHERE P.C_ID = C.C_ID AND ( P.P_ENDDATE IS NULL OR P.P_ENDDATE > NOW() ) AND P.U_ID_MANAGER = U.U_ID ORDER BY %s";

	$qr_pm_select_closed_projects_limited = "SELECT P.*, C.C_NAME FROM PROJECT P, CUSTOMER C, WBS_USER U WHERE P.C_ID = C.C_ID AND ( P.P_ENDDATE IS NOT NULL AND P.P_ENDDATE <= NOW() ) AND P.U_ID_MANAGER = U.U_ID AND C.C_STATUS = 0 ORDER BY %s";

	$qr_pm_close_project = "UPDATE PROJECT SET P_ENDDATE='!P_ENDDATE!', P_MODIFYDATETIME='!P_MODIFYDATETIME!', P_MODIFYUSERNAME='!P_MODIFYUSERNAME!' WHERE P_ID='!P_ID!'";
	
	$qr_pm_reopen_project = "UPDATE PROJECT SET P_ENDDATE=NULL, P_MODIFYDATETIME='!P_MODIFYDATETIME!', P_MODIFYUSERNAME='!P_MODIFYUSERNAME!' WHERE P_ID='!P_ID!'";

	$qr_pm_delete_project = "DELETE FROM PROJECT WHERE P_ID = '!P_ID!'";
	
	$qr_pm_delete_project_work = "DELETE FROM PROJECTWORK WHERE P_ID = '!P_ID!'";
	
	$qr_pm_delete_project_work_assignment = "DELETE FROM WORKASSIGNMENT WHERE P_ID = '!P_ID!'";

	$qr_pm_select_all_project_works = "SELECT * FROM PROJECTWORK WHERE P_ID = '!P_ID!'";
	
	$qr_pm_select_project_works = "SELECT * FROM PROJECTWORK WHERE P_ID = '!P_ID!' ORDER BY !ORDER_BY!";
	
	//$qr_pm_select_project_works_notcomplete = "SELECT * FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ENDDATE IS NULL ORDER BY !ORDER_BY!";

	$qr_pm_select_project_works_ordered = "SELECT *, ((PW_ENDDATE IS NOT NULL AND PW_DUEDATE IS NOT NULL AND PW_ENDDATE > PW_DUEDATE) OR (PW_ENDDATE IS NULL AND PW_DUEDATE < CURDATE())) as OVERDUE, (PW_ENDDATE IS NOT NULL AND PW_ENDDATE <= NOW()) AS COMPLETE FROM PROJECTWORK WHERE P_ID='!P_ID!' ORDER BY %s";

	$qr_pm_count_project_works = "SELECT COUNT(*) FROM PROJECTWORK WHERE P_ID = '!P_ID!'";

	$qr_pm_select_customers = "SELECT C_ID, C_NAME FROM CUSTOMER ORDER BY C_NAME";

	$qr_pm_select_active_customers = "SELECT C_ID, C_NAME FROM CUSTOMER WHERE C_STATUS=0 ORDER BY C_NAME";

	$qr_pm_select_managers = "SELECT U.U_ID, C.C_FIRSTNAME, C.C_MIDDLENAME, C.C_LASTNAME, C.C_EMAILADDRESS FROM WBS_USER U, CONTACT C WHERE (U.U_STATUS = 0 ) AND C.C_ID=U.C_ID ORDER BY C.C_FIRSTNAME, C.C_LASTNAME, C.C_MIDDLENAME";

	$qr_pm_select_project_startdate = "SELECT P_STARTDATE FROM PROJECT WHERE P_ID = '!P_ID!'";

	$qr_pm_select_project_enddate = "SELECT P_ID, P_ENDDATE FROM PROJECT WHERE P_ID = '!P_ID!'";

	//$qr_pm_select_projects = "SELECT P.P_ID, P.P_DESC, P.P_ENDDATE, C.C_NAME FROM PROJECT P, CUSTOMER C WHERE P.C_ID = C.C_ID AND C.C_STATUS = 0 ORDER BY %s";

	$qr_pm_count_projects = "SELECT COUNT(P_ID) FROM PROJECT";
	
	$qr_pm_count_active_projects = "SELECT COUNT(P_ID) FROM PROJECT WHERE P_ENDDATE IS NULL";

	$qr_pm_count_closed_projects = "SELECT COUNT(P_ID) FROM PROJECT WHERE P_ENDDATE IS NOT NULL";

	$qr_pm_select_project_count = "SELECT COUNT(P_ID) FROM PROJECT WHERE P_ID = '!P_ID!'";

	$qr_pm_select_project_customer = "SELECT C_ID FROM PROJECT WHERE P_ID='!P_ID!'";

	$qr_pm_select_project_active_works_count = "SELECT COUNT(*) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ENDDATE iS NULL";

	$qr_pm_select_users_project_rights = "SELECT U.*, C.*, PA.PA_RIGHTS FROM (WBS_USER U, CONTACT C) LEFT JOIN PACCESS PA ON PA.P_ID='!P_ID!' AND PA.U_ID = U.U_ID WHERE C.C_ID=U.C_ID AND (U_STATUS = 0 OR U_STATUS = 2) ORDER BY C_FIRSTNAME, C_LASTNAME, C_MIDDLENAME";

	$qr_pm_select_groups_project_rights = "SELECT UG.*, PA.PA_RIGHTS, COUNT(UGU.U_ID) AS USERCOUNT FROM UGROUP UG LEFT JOIN PGROUPACCESS PA ON PA.P_ID='!P_ID!' AND PA.UG_ID=UG.UG_ID LEFT JOIN UGROUP_USER UGU ON UGU.UG_ID=UG.UG_ID GROUP BY UG.UG_ID ORDER BY UG.UG_NAME";

	$qr_pm_delete_project_user_rights = "DELETE FROM PACCESS WHERE P_ID='!P_ID!'";

	$qr_pm_delete_project_group_rights = "DELETE FROM PGROUPACCESS WHERE P_ID='!P_ID!'";

	$qr_pm_insert_project_user_right = "INSERT INTO PACCESS(P_ID, U_ID, PA_RIGHTS) VALUES ('!P_ID!', '!U_ID!', '!PA_RIGHTS!')";

	$qr_pm_insert_project_group_right = "INSERT INTO PGROUPACCESS(P_ID, UG_ID, PA_RIGHTS) VALUES ('!P_ID!', '!UG_ID!', '!PA_RIGHTS!')";

	$qr_pm_extract_proj_user_sum_rights = "(IF 
											( 
												(SELECT UA.AR_VALUE FROM U_ACCESSRIGHTS AS UA WHERE AR_ID='!U_ID!' AND AR_PATH='/ROOT/PM/PROJECTS' AND AR_OBJECT_ID=P.P_ID) IS NULL, 0, 
												(SELECT UA.AR_VALUE FROM U_ACCESSRIGHTS AS UA WHERE AR_ID='!U_ID!' AND AR_PATH='/ROOT/PM/PROJECTS' AND AR_OBJECT_ID=P.P_ID) )
											|
											IF (
												(SELECT BIT_OR(UG.AR_VALUE) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
													AND UGU.U_ID='!U_ID!' AND UG.AR_OBJECT_ID=P.P_ID AND UG.AR_PATH='/ROOT/PM/PROJECTS' GROUP BY UGU.U_ID) IS NULL, 0,
													(SELECT BIT_OR(UG.AR_VALUE) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
													AND UGU.U_ID='!U_ID!' AND UG.AR_OBJECT_ID=P.P_ID AND UG.AR_PATH='/ROOT/PM/PROJECTS' GROUP BY UGU.U_ID) )) AS PA_RIGHT";

	$qr_pm_select_user_projects_ordered = "SELECT P.*, C.C_NAME, (P_ENDDATE <> '' and P_ENDDATE <= CURDATE()) as CLOSED, ".$qr_pm_extract_proj_user_sum_rights." FROM PROJECT P, CUSTOMER C WHERE P.C_ID = C.C_ID AND C.C_STATUS = 0 HAVING PA_RIGHT >= 0 ORDER BY (P_ENDDATE <> '' and P_ENDDATE <= CURDATE()), C.C_NAME, P.P_DESC";

	$qr_pm_select_user_projects_global_ordered = "SELECT P.*, C.C_NAME, (P_ENDDATE <> '' and P_ENDDATE <= CURDATE()) as CLOSED FROM PROJECT P, CUSTOMER C WHERE P.C_ID = C.C_ID AND C.C_STATUS = 0 ORDER BY (P_ENDDATE <> '' and P_ENDDATE <= CURDATE()), C.C_NAME, P.P_DESC";

	$qr_pm_select_user_project_right = "SELECT ".$qr_pm_extract_proj_user_sum_rights." FROM PROJECT P WHERE P.P_ID = '!P_ID!'";

	$qr_pm_select_project_is_closed = "SELECT (P_ENDDATE <= NOW() AND P_ENDDATE IS NOT NULL) FROM PROJECT WHERE P_ID='!P_ID!'";

	//
	// Work queries
	//
	
	$qr_pm_add_work = "INSERT INTO PROJECTWORK(P_ID, PW_ID, PW_DESC, PW_STARTDATE, PW_DUEDATE, PW_BILLABLE, PW_COSTESTIMATE, PW_COSTCUR) values ('!P_ID!', '!PW_ID!', '!PW_DESC!', '!PW_STARTDATE!', '!PW_DUEDATE!', '!PW_BILLABLE!', '!PW_COSTESTIMATE!', '!PW_COSTCUR!')";
	
	$qr_pm_modify_work = "UPDATE PROJECTWORK SET PW_DESC='!PW_DESC!', PW_BILLABLE='!PW_BILLABLE!', PW_DUEDATE='!PW_DUEDATE!', PW_COSTESTIMATE='!PW_COSTESTIMATE!', PW_COSTCUR = '!PW_COSTCUR!', PW_STARTDATE='!PW_STARTDATE!' WHERE PW_ID='!PW_ID!' AND P_ID='!P_ID!'";
	
	$qr_pm_select_work = "SELECT PW.*, P.P_ENDDATE, P.P_DESC, P.P_ID, P.U_ID_MANAGER, C.C_NAME FROM PROJECTWORK PW, PROJECT P, CUSTOMER C WHERE PW.PW_ID = '!PW_ID!' AND PW.P_ID='!P_ID!' AND P.P_ID = '!P_ID!' AND C.C_ID = P.C_ID";

	$qr_pm_finish_work = "UPDATE PROJECTWORK SET PW_ENDDATE='!PW_ENDDATE!' WHERE PW_ID='!PW_ID!' AND P_ID='!P_ID!'";

	$qr_pm_reopen_work = "UPDATE PROJECTWORK SET PW_ENDDATE=NULL WHERE PW_ID='!PW_ID!' AND P_ID='!P_ID!'";

	$qr_pm_delete_work = "DELETE FROM PROJECTWORK WHERE PW_ID = '!PW_ID!' AND P_ID='!P_ID!'";
	
	$qr_pm_delete_work_assignment = "DELETE FROM WORKASSIGNMENT WHERE PW_ID = '!PW_ID!' AND P_ID='!P_ID!'";

	$qr_pm_select_work_asgn = "SELECT WA.* FROM WORKASSIGNMENT WA, WBS_USER U, CONTACT C WHERE C.C_ID=U.C_ID AND WA.P_ID = '!P_ID!' AND WA.PW_ID = '!PW_ID!' AND U.U_ID=WA.U_ID ORDER BY C.C_LASTNAME, C.C_FIRSTNAME, C.C_MIDDLENAME";

	$qr_pm_select_work_startdate = "SELECT PW_STARTDATE FROM PROJECTWORK WHERE PW_ID = '!PW_ID!' AND P_ID='!P_ID!'";

	$qr_pm_select_work_short = "SELECT * FROM PROJECTWORK WHERE PW_ID='!PW_ID!' AND P_ID='!P_ID!'";

	$qr_pm_select_work_count = "SELECT COUNT(PW_ID) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ID = '!PW_ID!'";

	$qr_pm_select_work_curency_count = "SELECT COUNT(*) FROM PROJECTWORK WHERE PW_COSTCUR='!CUR_ID!' AND PW_COSTESTIMATE IS NOT NULL";

	$qr_pm_select_min_project_work_startdate = "SELECT MIN(PW_STARTDATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!'";

	$qr_pm_select_min_project_work_startdate_filtered = "SELECT MIN(PW_STARTDATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!' %s";

	$qr_pm_select_max_work_enddate = "SELECT MAX(PW_ENDDATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!'";

	$qr_pm_select_max_work_enddate_filtered = "SELECT MAX(PW_ENDDATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!' %s";

	$qr_pm_select_max_work_duedate = "SELECT MAX(PW_DUEDATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!'";

	$qr_pm_select_max_work_duedate_filtered = "SELECT MAX(PW_DUEDATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!' %s";

	$qr_pm_select_active_works = "SELECT * FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ENDDATE iS NULL";

	//
	// Assignment queries
	//

	$qr_pm_add_asgn = "INSERT INTO WORKASSIGNMENT(P_ID, PW_ID, U_ID) VALUES ('!P_ID!', '!PW_ID!', '!U_ID!')";

	$qr_pm_select_work_asgnlist = "SELECT WA.U_ID, C.C_LASTNAME, C.C_FIRSTNAME, C.C_MIDDLENAME, C.C_EMAILADDRESS FROM WORKASSIGNMENT WA, WBS_USER U, CONTACT C WHERE C.C_ID=U.C_ID AND U.U_ID=WA.U_ID AND WA.P_ID='!P_ID!' ORDER BY C.C_FIRSTNAME, C.C_LASTNAME, C.C_MIDDLENAME, C.C_EMAILADDRESS";
	
	$qr_pm_select_asgn_list = "SELECT U.U_ID FROM WBS_USER U, CONTACT C WHERE C.C_ID = U.C_ID ORDER BY C.C_FIRSTNAME, C.C_LASTNAME, C.C_MIDDLENAME, C.C_EMAILADDRESS";

	$qr_pm_select_work_asgn = "SELECT U_ID FROM WORKASSIGNMENT WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' ORDER BY U_ID";
	
	//$qr_pm_select_projectworks_asgn = "SELECT U_ID, PW_ID FROM WORKASSIGNMENT WHERE P_ID='!P_ID!' ORDER BY U_ID";

	$qr_pm_delete_work_asgn = "DELETE FROM WORKASSIGNMENT WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_pm_delete_asgn = "DELETE FROM WORKASSIGNMENT WHERE P_ID = '!P_ID!' AND PW_ID = '!PW_ID!' AND U_ID = '!U_ID!'";
	
	$qr_pm_select_project_asng = "SELECT WA.U_ID,PW.* FROM PROJECTWORK PW LEFT JOIN WORKASSIGNMENT WA ON (WA.P_ID=PW.P_ID AND WA.PW_ID=PW.PW_ID) LEFT JOIN WBS_USER U ON (WA.U_ID=U.U_ID AND (U.U_STATUS = 0 ))  WHERE PW.P_ID='!P_ID!' ORDER BY U_ID";
	$qr_pm_select_project_asng_notcomplete = "SELECT WA.U_ID,PW.* FROM PROJECTWORK PW LEFT JOIN WORKASSIGNMENT WA ON (WA.P_ID=PW.P_ID AND WA.PW_ID=PW.PW_ID) LEFT JOIN WBS_USER U ON (WA.U_ID=U.U_ID AND (U.U_STATUS = 0 ))  WHERE PW.P_ID='!P_ID!' AND PW.PW_ENDDATE IS NULL ORDER BY U_ID";

	$qr_pm_selectAsgn_P_DESC_PW_DESC = "SELECT P.P_DESC, PW.PW_DESC FROM PROJECT P, PROJECTWORK PW WHERE P.P_ID = '!P_ID!' AND PW.PW_ID = '!PW_ID!'";

	$qr_pm_select_all_projects_asgnlist = "SELECT WA.U_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME, CA.C_EMAILADDRESS FROM WORKASSIGNMENT WA, PROJECT P, CUSTOMER C, WBS_USER U, CONTACT CA WHERE CA.C_ID=U.C_ID AND U.U_ID=WA.U_ID AND WA.P_ID = P.P_ID AND C.C_ID = P.C_ID AND C.C_STATUS = 0 ORDER BY U_ID";

	$qr_pm_select_closed_projects_asgnlist = "SELECT WA.U_ID, WA.P_ID, P.P_ID, P.P_ENDDATE FROM WORKASSIGNMENT WA, PROJECT P, CUSTOMER C WHERE WA.P_ID = P.P_ID AND P.P_ENDDATE IS NOT NULL AND C.C_ID = P.C_ID AND C.C_STATUS = 0 ORDER BY U_ID";

	$qr_pm_select_active_projects_asgnlist = "SELECT WA.U_ID, WA.P_ID, P.P_ID, P.P_ENDDATE FROM WORKASSIGNMENT WA, PROJECT P, CUSTOMER C WHERE WA.P_ID = P.P_ID AND P.P_ENDDATE IS NULL AND C.C_ID = P.C_ID AND C.C_STATUS = 0 ORDER BY U_ID";
	
	//
	// Gantt queries
	//

	$qr_pm_select_project_works_gantt_chart = "SELECT *, (PW_ENDDATE IS NOT NULL AND PW_DUEDATE IS NOT NULL AND PW_ENDDATE > PW_DUEDATE ) as OVERDUE, (PW_ENDDATE IS NOT NULL AND PW_ENDDATE <= NOW()) AS COMPLETE FROM PROJECTWORK WHERE P_ID = '!P_ID!' ORDER BY %s";

	$qr_pm_datediff = "SELECT TO_DAYS('!END!') - TO_DAYS('!START!')";


	$qr_pm_select_gantt_works = "SELECT *, 
									IF ( (TO_DAYS(PW_STARTDATE) - TO_DAYS('!START!')) <= (TO_DAYS('!END!') - TO_DAYS('!START!')), 
											TO_DAYS(PW_STARTDATE) - TO_DAYS('!START!'), 
											TO_DAYS('!END!') - TO_DAYS('!START!') + 1 ) as START_SPAN,

									IF ( PW_DUEDATE IS NOT NULL, 
										IF ( PW_DUEDATE >= '!START!', 
											IF ( '!START!' < PW_STARTDATE, (TO_DAYS(PW_DUEDATE) - TO_DAYS(PW_STARTDATE)) + 1, TO_DAYS(PW_DUEDATE) - TO_DAYS('!START!') + 1 ), NULL ), 
											NULL
										 ) as DUE_SPAN,

									( PW_DUEDATE IS NULL AND PW_STARTDATE >= NOW() ) as DUMMY_DAY,

									IF ( PW_DUEDATE IS NOT NULL AND ((PW_ENDDATE IS NOT NULL AND PW_ENDDATE > PW_DUEDATE) || (PW_ENDDATE IS NULL AND NOW() > PW_DUEDATE)),
										 IF ( PW_ENDDATE IS NOT NULL, TO_DAYS(PW_ENDDATE) - TO_DAYS(PW_DUEDATE), TO_DAYS(NOW()) - TO_DAYS(PW_DUEDATE) ), 
										 NULL ) as OVERDUE_SPAN,

									IF ( PW_ENDDATE IS NOT NULL, 
										IF ( PW_ENDDATE >= '!START!', 
											IF ( '!START!' < PW_STARTDATE, 
												TO_DAYS(PW_ENDDATE) - TO_DAYS(PW_STARTDATE) + 1, 
												TO_DAYS(PW_ENDDATE) - TO_DAYS('!START!') + 1 ), NULL ),

										IF ( PW_STARTDATE < NOW(), 
											IF ( '!START!' < PW_STARTDATE, 
												TO_DAYS(NOW()) - TO_DAYS(PW_STARTDATE) + 1,
												TO_DAYS(NOW()) - TO_DAYS('!START!') + 1 )
											, 1 )

									) as ACTUAL_SPAN,

									(TO_DAYS(PW_STARTDATE) - TO_DAYS('!START!') + 1) AS START_OFFSET,
									(TO_DAYS(PW_DUEDATE) - TO_DAYS('!START!') + 1) AS DUE_OFFSET,
									(TO_DAYS(PW_DUEDATE) - TO_DAYS(PW_STARTDATE) + 1) AS ACTUAL_DUE,

									IF ( PW_ENDDATE IS NOT NULL, TO_DAYS('!END!') - TO_DAYS(PW_ENDDATE), TO_DAYS('!END!') - TO_DAYS(NOW()) ) as END_SPAN,
									(PW_DUEDATE < NOW()) as OVERDUE, 

									(PW_ENDDATE IS NOT NULL AND PW_ENDDATE <= NOW()) AS COMPLETE,

									IF ( PW_ENDDATE IS NOT NULL, TO_DAYS(PW_ENDDATE) - TO_DAYS(PW_STARTDATE) + 1, 
										IF ( PW_STARTDATE <= NOW(), TO_DAYS(NOW()) - TO_DAYS(PW_STARTDATE) + 1, NULL ) ) AS ACTUAL_LENGTH

								FROM PROJECTWORK WHERE P_ID='!P_ID!' %s ORDER BY %s";

	$qr_pm_completeFilter = "AND (NOT (PW_ENDDATE IS NOT NULL AND PW_ENDDATE <= NOW()))";

	//
	// Common queries
	//

	$qr_pm_findNextId = "SELECT MAX(%s) FROM %s";

	$qr_pm_findWorkId = "SELECT MAX(PW_ID) FROM PROJECTWORK WHERE P_ID='!P_ID!'";

	$qr_pm_findMax_projectWorkId = "SELECT MAX(PW_ID) FROM PROJECTWORK WHERE P_ID='!P_ID!'";

	$qr_pm_select_user = "SELECT * FROM WBS_USER WHERE U_ID='!U_ID!'";

	$qr_pm_select_currency_list = "SELECT * FROM CURRENCY";

	//
	// Event handlers queries
	//

	$qr_pm_select_user_open_work = "SELECT COUNT(*) FROM WORKASSIGNMENT WA, PROJECTWORK PW WHERE WA.U_ID = '!U_ID!' AND PW.P_ID <> 0 AND PW.PW_ID = WA.PW_ID AND PW.P_ID=WA.P_ID AND PW.PW_ENDDATE IS NULL";

	$qr_pm_select_user_work = "SELECT COUNT(*) FROM WORKASSIGNMENT WA WHERE WA.U_ID = '!U_ID!'";

	$qr_pm_select_user_open_project = "SELECT COUNT(*) FROM PROJECT WHERE U_ID_MANAGER='!U_ID!' AND P_ENDDATE IS NULL";

	$qr_pm_select_user_project = "SELECT COUNT(*) FROM PROJECT WHERE U_ID_MANAGER='!U_ID!'";

	$qr_pm_delete_user_assignments = "DELETE FROM WORKASSIGNMENT WHERE U_ID='!U_ID!'";

	//
	// Project statistics
	//

	$qr_pm_count_project_total_work = "SELECT COUNT(*) FROM PROJECTWORK WHERE P_ID = '!P_ID!'";
	
	$qr_pm_count_project_in_progress_work = "SELECT COUNT(*) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ENDDATE IS NULL";

	$qr_pm_count_project_closed_work = "SELECT COUNT(*) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ENDDATE IS NOT NULL";

	$qr_pm_count_project_overdue_work = "SELECT COUNT(*) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND ((PW_DUEDATE < NOW() AND PW_ENDDATE IS NULL) OR (PW_DUEDATE < PW_ENDDATE))";

	$qr_pm_select_project_billable = "SELECT P_BILLABLE FROM PROJECT WHERE P_ID = '!P_ID!'";

	$qr_pm_select_project_total_work_cost = "SELECT SUM(PW_COSTESTIMATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_COSTCUR = '%s'";

	$qr_pm_select_project_in_progress_work_cost = "SELECT SUM(PW_COSTESTIMATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ENDDATE IS NULL AND PW_COSTCUR = '%s'";

	$qr_pm_select_project_closed_work_cost = "SELECT SUM(PW_COSTESTIMATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND PW_ENDDATE IS NOT NULL AND PW_COSTCUR = '%s'";

	$qr_pm_select_project_overdue_work_cost = "SELECT SUM(PW_COSTESTIMATE) FROM PROJECTWORK WHERE P_ID = '!P_ID!' AND ((PW_DUEDATE < NOW() AND PW_ENDDATE IS NULL) OR (PW_DUEDATE < PW_ENDDATE)) AND PW_COSTCUR =' %s'";

	$qr_pm_select_project_work_user = "SELECT WA.U_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME, CA.C_EMAILADDRESS FROM WORKASSIGNMENT WA LEFT JOIN WBS_USER U ON U.U_ID=WA.U_ID LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID WHERE WA.P_ID = '!P_ID!'";
	
	global $qr_pm_unset_project_ddfolder;
	$qr_pm_unset_project_ddfolder = "UPDATE PROJECT SET DF_ID=NULL WHERE DF_ID='!DF_ID!'";

?>