DROP TABLE IF EXISTS CLIST;
CREATE TABLE CLIST (
  `CL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CL_NAME` varchar(50) DEFAULT NULL,
  `CL_C_ID` int(11) NOT NULL,
  `CL_SHARED` smallint(6) DEFAULT '0',
  `CL_MODIFYDATETIME` datetime DEFAULT NULL,
  `CL_MODIFYCID` int(11) DEFAULT NULL,
  `CL_SQL` text NOT NULL,
  `CL_SEARCH` text NOT NULL,
  PRIMARY KEY (`CL_ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CLIST_CONTACT;
CREATE TABLE CLIST_CONTACT
(
  CL_ID INT NOT NULL,
  C_ID INT NOT NULL,
  CLC_MODIFYDATETIME DATETIME NULL,
  CLC_MODIFYUSERNAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (CL_ID, C_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CONTACTNOTE;
CREATE TABLE CONTACTNOTE (
  `CN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CN_CID` int(11) NOT NULL,
  `CN_TEXT` text NOT NULL,
  `CN_CREATECID` int(11) NOT NULL,
  `CN_CREATETIME` datetime NOT NULL,
  PRIMARY KEY (`CN_ID`),
  KEY `CN_CID` (`CN_CID`),
  KEY `CN_CREATETIME` (`CN_CREATETIME`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
