<?php

	//
	// Quick Notes application SQL queries
	//

	$qr_mm_maxNoteID = "SELECT MAX(MMM_ID) FROM MMMESSAGE";

	$qr_mm_insertNote = "INSERT INTO MMMESSAGE ( MMM_ID , MMF_ID , MMM_SUBJECT , MMM_FROM , MMM_CONTENT , MMM_STATUS , MMM_PRIORITY , MMM_ATTACHMENT , MMM_IMAGES , MMM_DATETIME, MMM_USERID , MMM_TO ) VALUES
		( '!MMM_ID!', '!MMF_ID!', '!MMM_SUBJECT!', '!MMM_FROM!', '!MMM_CONTENT!', '!MMM_STATUS!', '!MMM_PRIORITY!', '!MMM_ATTACHMENT!', '!MMM_IMAGES!', '!MMM_DATETIME!', '!MMM_USERID!', '!MMM_TO!' )";

	$qr_mm_updateNote = "UPDATE MMMESSAGE SET MMM_SUBJECT='!MMM_SUBJECT!', MMM_FROM='!MMM_FROM!', MMM_CONTENT='!MMM_CONTENT!', MMM_STATUS='!MMM_STATUS!', MMM_PRIORITY='!MMM_PRIORITY!', MMM_ATTACHMENT='!MMM_ATTACHMENT!', MMM_IMAGES='!MMM_IMAGES!', MMM_STATUS='!MMM_STATUS!', MMM_TO='!MMM_TO!', MMM_DATETIME='!MMM_DATETIME!' WHERE MMM_ID='!MMM_ID!'";

	$qr_mm_deleteMessage = "DELETE FROM MMMESSAGE WHERE MMM_ID='!MMM_ID!'";
	$qr_mm_deleteSentTo = "DELETE FROM MMMSENTTO WHERE MMM_ID='!MMM_ID!'";

	$qr_mm_updateNoteLocation = "UPDATE MMMESSAGE SET MMF_ID='!MMF_ID!', MMM_CONTENT='!MMM_CONTENT!' WHERE MMM_ID='!MMM_ID!'";

	$qr_mm_findNotes = "SELECT MM.*, MMF.MMF_NAME, (SELECT IF ( UA.AR_VALUE IS NULL, 0, UA.AR_VALUE ) | IF ( (SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) IS NULL, 0, (SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) ) FROM U_ACCESSRIGHTS AS UA WHERE AR_ID='!U_ID!' AND AR_PATH='/ROOT/MM/FOLDERS' AND AR_OBJECT_ID=MM.MMF_ID) AS TREE_ACCESS_RIGHTS FROM MMMESSAGE MM, MMFOLDER MMF WHERE (LOWER(MMM_SUBJECT) LIKE '!SEARCHSTR!' OR LOWER(MMM_CONTENT) LIKE '!SEARCHSTR1!') AND MMF.MMF_ID=MM.MMF_ID HAVING TREE_ACCESS_RIGHTS  > 0 ORDER BY %s";

	$qr_mm_findNotesGlobal = "SELECT MM.*, MMF.MMF_NAME, 7 as TREE_ACCESS_RIGHTS FROM MMMESSAGE MM, MMFOLDER MMF WHERE (LOWER(MMM_SUBJECT) LIKE '!SEARCHSTR!' OR LOWER(MMM_CONTENT) LIKE '!SEARCHSTR1!') AND MMF.MMF_ID=MM.MMF_ID";

	$qr_mm_selectedNotes = "SELECT MM.*, MMF.MMF_NAME, MMA.MMA_RIGHTS FROM MMMESSAGE MM, MMACCESS MMA, MMFOLDER MMF WHERE %s AND MMA.MMF_ID=MM.MMF_ID AND MMA.U_ID='!U_ID!' AND MMF.MMF_ID=MM.MMF_ID ORDER BY %s";

	$qr_mm_selectFolderContacts = "SELECT C.* FROM CONTACT C WHERE C_EMAILADDRESS IS NOT NULL AND C.CF_ID='!CF_ID!' AND C_EMAILADDRESS <> \"\" ORDER BY UPPER(CONCAT(IF(C_FIRSTNAME is not null, C_FIRSTNAME, ''), IF(C_MIDDLENAME is not null, C_MIDDLENAME, ''), IF(C_LASTNAME is not null, C_LASTNAME, ''), IF(C_EMAILADDRESS is not null, C_EMAILADDRESS, '')))";

	$qr_mm_selectUsersContacts = "SELECT C.* FROM CONTACT C, WBS_USER U WHERE C_EMAILADDRESS IS NOT NULL AND C.CF_ID=\"1.\" AND U.C_ID=C.C_ID AND U.U_STATUS <> 1 ORDER  BY UPPER(CONCAT(IF(C_FIRSTNAME is not null, C_FIRSTNAME, ''), IF(C_MIDDLENAME is not null, C_MIDDLENAME, ''), IF(C_LASTNAME is not null, C_LASTNAME, ''), IF(C_EMAILADDRESS is not null, C_EMAILADDRESS, '')))";

	$qr_mm_selectSenders = "SELECT * FROM MMSENDER";

	$qr_mm_selectSender = "SELECT * FROM MMSENDER WHERE MMS_ID='!MMS_ID!'";

	$qr_mm_deleteSender = "DELETE FROM MMSENDER WHERE MMS_ID='!MMS_ID!'";

	$qr_mm_insertSender = "INSERT INTO MMSENDER ( MMS_FROM, MMS_EMAIL, MMS_REPLYTO, MMS_RETURNPATH, MMS_LANGUAGE, MMS_ENCODING ) VALUES ('!MMS_FROM!', '!MMS_EMAIL!', '!MMS_REPLYTO!', '!MMS_RETURNPATH!', '!MMS_LANGUAGE!', '!MMS_ENCODING!')";

	$qr_mm_updateSender = "UPDATE MMSENDER SET MMS_FROM='!MMS_FROM!', MMS_EMAIL='!MMS_EMAIL!', MMS_REPLYTO='!MMS_REPLYTO!', MMS_RETURNPATH='!MMS_RETURNPATH!', MMS_LANGUAGE='!MMS_LANGUAGE!', MMS_ENCODING='!MMS_ENCODING!' WHERE MMS_ID='!MMS_ID!'";


	$qr_mm_selectAccountsList = "SELECT * FROM MMACCOUNT ORDER BY MMA_NAME ASC";

	$qr_mm_selectAccountByEmail = "SELECT * FROM MMACCOUNT WHERE MMA_EMAIL='!MMM_ACCOUNT!' OR CONCAT(MMA_EMAIL, '@', MMA_DOMAIN)='!MMM_ACCOUNT!' LIMIT 1";

	$qr_mm_selectAccount = "SELECT * FROM MMACCOUNT WHERE MMA_ID='!MMA_ID!'";

	$qr_mm_deleteSender = "DELETE FROM MMACCOUNT WHERE MMA_ID='!MMA_ID!'";

	$qr_mm_insertAccount = "INSERT INTO MMACCOUNT SET MMA_NAME='!MMA_NAME!', MMA_EMAIL='!MMA_EMAIL!',
		MMA_DOMAIN='!MMA_DOMAIN!', MMA_SERVER='!MMA_SERVER!', MMA_LOGIN='!MMA_LOGIN!', MMA_PASSWORD='!MMA_PASSWORD!',
		MMA_PORT='!MMA_PORT!', MMA_PROTOCOL='!MMA_PROTOCOL!', MMA_SECURE='!MMA_SECURE!',
		MMA_INTERNAL='!MMA_INTERNAL!', MMA_USERID='!MMA_USERID!', MMA_ACCESS='!MMA_ACCESS!'";

	$qr_mm_updateAccount = "UPDATE MMACCOUNT SET MMA_NAME='!MMA_NAME!',
		MMA_EMAIL='!MMA_EMAIL!', MMA_DOMAIN='!MMA_DOMAIN!',
		MMA_SERVER='!MMA_SERVER!', MMA_LOGIN='!MMA_LOGIN!', MMA_PASSWORD='!MMA_PASSWORD!',
		MMA_PORT='!MMA_PORT!', MMA_PROTOCOL='!MMA_PROTOCOL!', MMA_SECURE='!MMA_SECURE!',
		MMA_INTERNAL='!MMA_INTERNAL!', MMA_ACCESS='!MMA_ACCESS!'
		WHERE MMA_ID='!MMA_ID!'";

	$qr_mm_updateAccount_wo_pass = "UPDATE MMACCOUNT SET MMA_NAME='!MMA_NAME!',
		MMA_EMAIL='!MMA_EMAIL!', MMA_DOMAIN='!MMA_DOMAIN!',
		MMA_SERVER='!MMA_SERVER!', MMA_LOGIN='!MMA_LOGIN!',
		MMA_PORT='!MMA_PORT!', MMA_PROTOCOL='!MMA_PROTOCOL!', MMA_SECURE='!MMA_SECURE!',
		MMA_INTERNAL='!MMA_INTERNAL!' WHERE MMA_ID='!MMA_ID!'";

	$qr_mm_deleteAccount = "DELETE FROM MMACCOUNT WHERE MMA_ID='!MMA_ID!' LIMIT 1";

	$qr_mm_updateMessageImages = "UPDATE MMMESSAGE SET MMM_IMAGES='!MMM_IMAGES!' WHERE MMM_ID='!MMM_ID!'";

	$qr_mm_insertSentItem = "INSERT INTO MMMSENTTO ( MMM_ID, MMMST_EMAIL, MMMST_STATUS, MMMST_OPENED ) VALUES (  '!MMM_ID!',  '!MMMST_EMAIL!', '!MMMST_STATUS!', '!MMMST_OPENED!' )";

	$qr_mm_selectSendStat = "SELECT * FROM MMMSENTTO WHERE MMM_ID='!MMM_ID!' ORDER BY MMMST_EMAIL ASC";

	$qr_mm_selectStatCount = "SELECT COUNT(*) AS CNT, MMMST_STATUS FROM MMMSENTTO WHERE MMM_ID='!MMM_ID!' GROUP BY MMMST_STATUS";

	$qr_mm_deleteStat = "DELETE FROM MMMSENTTO WHERE MMM_ID='!MMM_ID!'";

	$qr_mm_selectTplsInFolders = "SELECT * FROM MMMESSAGE WHERE MMF_ID IN ( %s ) AND MMM_STATUS=100 ORDER BY MMM_SUBJECT";

	$qr_mm_pendingNotesToSend = "SELECT * FROM MMMESSAGE WHERE MMM_STATUS=1 AND MMM_DATETIME <= NOW() ";

	$qr_mm_selectSentMessagesCount = "SELECT COUNT(*) FROM MMMSENTTO WHERE MMMST_DATE='!DATE!'";
	$qr_mm_selectPendMessagesCount = "SELECT COUNT(*) FROM MMMESSAGE WHERE MMM_STATUS=1 AND DATE(MMM_DATETIME)=DATE('!DATE!')";

	$qr_mm_deleteCache = "DELETE FROM MMCACHE WHERE MMC_ACCOUNT='!MMC_ACCOUNT!'";

	$qr_mm_deleteCacheMessage = "DELETE FROM MMCACHE WHERE MMC_UID='!MMC_UID!' AND MMC_ACCOUNT='!MMC_ACCOUNT!'";

?>