<?php

	//
	// Quick Notes application SQL queries
	//

	$qr_qn_maxNoteID = "SELECT MAX(QN_ID) FROM QUICKNOTES";

	$qr_qn_insertNote = "INSERT INTO QUICKNOTES(QN_ID, QNF_ID, QN_SUBJECT, QN_CONTENT, QN_ATTACHMENT, QN_MODIFYDATETIME, QN_MODIFYUSERNAME, QN_STATUS) VALUES ('!QN_ID!', '!QNF_ID!', '!QN_SUBJECT!', '!QN_CONTENT!', '!QN_ATTACHMENT!', '!QN_MODIFYDATETIME!', '!QN_MODIFYUSERNAME!', '!QN_STATUS!')";

	$qr_qn_updateNote = "UPDATE QUICKNOTES SET QN_SUBJECT='!QN_SUBJECT!', QN_CONTENT='!QN_CONTENT!', QN_ATTACHMENT='!QN_ATTACHMENT!', QN_MODIFYDATETIME='!QN_MODIFYDATETIME!', QN_MODIFYUSERNAME='!QN_MODIFYUSERNAME!' WHERE QN_ID='!QN_ID!'";

	$qr_qn_deleteNote = "DELETE FROM QUICKNOTES WHERE QN_ID='!QN_ID!'";

	$qr_qn_updateNoteLocation = "UPDATE QUICKNOTES SET QN_MODIFYDATETIME=now(), QN_MODIFYUSERNAME='!QN_MODIFYUSERNAME!', QNF_ID='!QNF_ID!' WHERE QN_ID='!QN_ID!'";

	$qr_qn_totalRights = "(SELECT
							IF ( UA.AR_VALUE IS NULL, 0, UA.AR_VALUE ) |
							IF ( (SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
							AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) IS NULL, 0, 
							(SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
							AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) )
							FROM U_ACCESSRIGHTS AS UA WHERE AR_ID='!U_ID!' AND AR_PATH='/ROOT/QN/FOLDERS' AND AR_OBJECT_ID=QNF.QNF_ID)
							";

	$qr_qn_findNotes = "SELECT QN.*, QNF.QNF_NAME, ".$qr_qn_totalRights." AS TREE_ACCESS_RIGHTS FROM QUICKNOTES QN, QNFOLDER QNF WHERE (LOWER(QN_SUBJECT) LIKE '!SEARCHSTR!' OR LOWER(QN_CONTENT) LIKE '!SEARCHSTR1!') AND QNF.QNF_ID=QN.QNF_ID HAVING TREE_ACCESS_RIGHTS > 0 ORDER BY  %s ";

	$qr_qn_globalFindNotes = "SELECT QN.*, QNF.QNF_NAME FROM QUICKNOTES QN, QNFOLDER QNF WHERE (LOWER(QN_SUBJECT) LIKE '!SEARCHSTR!' OR LOWER(QN_CONTENT) LIKE '!SEARCHSTR1!') AND QNF.QNF_ID=QN.QNF_ID ORDER BY  %s";

	$qr_qn_findGroupNotes = "SELECT QN.*, QNF.QNF_NAME, MAX(QNGA.QNA_RIGHTS) AS QNA_RIGHTS FROM QNGROUPACCESS QNGA, UGROUP_USER UGU, QUICKNOTES QN, QNFOLDER QNF WHERE (LOWER(QN_SUBJECT) LIKE '!SEARCHSTR!' OR LOWER(QN_CONTENT) LIKE '!SEARCHSTR1!') AND QN.QNF_ID = QNGA.QNF_ID AND QNGA.UG_ID = UGU.UG_ID AND UGU.U_ID = '!U_ID!' AND QNF.QNF_ID=QN.QNF_ID GROUP BY QN.QN_ID ORDER BY %s";

	$qr_qn_selectedNotes = "SELECT QN.*, QNF.QNF_NAME FROM QUICKNOTES QN, QNFOLDER QNF WHERE %s AND QNF.QNF_ID=QN.QNF_ID ORDER BY %s";

	$qr_qn_tplList = "SELECT * FROM QNTEMPLATE ORDER BY QNT_NAME ASC";

	$qr_qn_getTpl = "SELECT * FROM QNTEMPLATE WHERE QNT_ID='!QNT_ID!'";

	$qr_qn_deleteTpl = "DELETE FROM QNTEMPLATE WHERE QNT_ID='!QNT_ID!'";

	$qr_qn_insertTpl = "INSERT INTO QNTEMPLATE( QNT_NAME , QNT_HTML, QNT_MODIFYDATETIME,  QNT_MODIFYUSERNAME ) VALUES ( '!QNT_NAME!', '!QNT_HTML!', '!QNT_MODIFYDATETIME!', '!QNT_MODIFYUSERNAME!')";

	$qr_qn_updateTpl = "UPDATE QNTEMPLATE SET QNT_NAME='!QNT_NAME!', QNT_HTML='!QNT_HTML!', QNT_MODIFYDATETIME='!QNT_MODIFYDATETIME!', QNT_MODIFYUSERNAME='!QNT_MODIFYUSERNAME!' WHERE QNT_ID='!QNT_ID!'";

?>