<?php

	$qr_qp_maxNoteID = "SELECT MAX(QP_ID) FROM QUICKPAGES";

	$qr_qp_maxSort   = "SELECT MAX(QPF_SORT) FROM QPFOLDER WHERE QPF_ID_PARENT='!QPF_ID_PARENT!' AND QPB_ID='!QPB_ID!'";

	$qr_qp_insertNote = "INSERT INTO QUICKPAGES(QP_ID, QPF_ID, QP_TITLE, QP_KEYWORDS, QP_DESCRIPTION, QP_CONTENT, QP_ATTACHMENT, QP_MODIFYDATETIME, QP_MODIFYUSERNAME, QP_STATUS) VALUES ('!QP_ID!', '!QPF_ID!', '!QP_TITLE!', '!QP_KEYWORDS!', '!QP_DESCRIPTION!','!QP_CONTENT!', '!QP_ATTACHMENT!', '!QP_MODIFYDATETIME!', '!QP_MODIFYUSERNAME!', '!QP_STATUS!')";

	$qr_qp_updateNote = "UPDATE QUICKPAGES SET QP_TITLE='!QP_TITLE!', QP_KEYWORDS='!QP_KEYWORDS!', QP_DESCRIPTION='!QP_DESCRIPTION!', QP_CONTENT='!QP_CONTENT!', QP_ATTACHMENT='!QP_ATTACHMENT!', QP_MODIFYDATETIME='!QP_MODIFYDATETIME!', QP_MODIFYUSERNAME='!QP_MODIFYUSERNAME!' WHERE QP_ID='!QP_ID!'";

	$qr_qp_deleteNote = "DELETE FROM QUICKPAGES WHERE QP_ID='!QP_ID!'";

	$qr_qp_updateNoteLocation = "UPDATE QUICKPAGES SET QP_MODIFYDATETIME=now(), QP_MODIFYUSERNAME='!QP_MODIFYUSERNAME!', QPF_ID='!QPF_ID!' WHERE QP_ID='!QP_ID!'";

	$qr_qp_selectedNotes = "SELECT QP.*, QPF.QPF_NAME, QPA.QPA_RIGHTS FROM QUICKNOTES QP, QPACCESS QPA, QPFOLDER QPF WHERE %s AND QPA.QPF_ID=QP.QPF_ID AND QPA.U_ID='!U_ID!' AND QPF.QPF_ID=QP.QPF_ID ORDER BY %s";

	$qr_qp_maxBookID = "SELECT MAX(QPB_ID) FROM QPBOOK";

	$qr_qp_insertBook = "INSERT INTO QPBOOK( QPB_ID, QPB_NAME, QPB_ID_PARENT, QPB_STATUS, QPB_TITLE, QPB_KEYWORDS, QPB_DESCRIPTION, QPB_PUBLISHED, QPB_PROPERTIES ) VALUES ('!QPB_ID!', '!QPB_NAME!', '!QPB_ID_PARENT!', '!QPB_STATUS!', '!QPB_TITLE!', '!QPB_KEYWORDS!', '!QPB_DESCRIPTION!', '!QPB_PUBLISHED!', '!QPB_PROPERTIES!' )";

	$qr_qp_updateBook = "UPDATE QPBOOK SET QPB_NAME='!QPB_NAME!', QPB_TEXTID='!QPB_TEXTID!', QPB_ID_PARENT='!QPB_ID_PARENT!', QPB_STATUS='!QPB_STATUS!', QPB_TITLE='!QPB_TITLE!', QPB_KEYWORDS='!QPB_KEYWORDS!', QPB_DESCRIPTION='!QPB_DESCRIPTION!', QPB_PUBLISHED='!QPB_PUBLISHED!', QPB_PROPERTIES='!QPB_PROPERTIES!', QPB_THEME='!QPB_THEME!' WHERE QPB_ID='!QPB_ID!'";

	$qr_qp_updateBookProperties = "UPDATE QPBOOK SET QPB_PROPERTIES='!QPB_PROPERTIES!' WHERE QPB_ID='!QPB_ID!'";

	$qr_qp_deleteBook = "DELETE FROM QPBOOK WHERE QPB_ID='!QPB_ID!'";

	$qr_qp_updateFolderBook = "UPDATE QPFOLDER SET QPB_ID='!QPB_ID!', QPF_TEXTID='!QPF_TEXTID!', QPF_NAME='!QPF_NAME!', QPF_CONTENT='!QPF_CONTENT!', QPF_TEXT='!QPF_TEXT!', QPF_TITLE='!QPF_TITLE!', QPF_KEYWORDS='!QPF_KEYWORDS!', QPF_DESCRIPTION='!QPF_DESCRIPTION!', QPF_AUX1='!QPF_AUX1!', QPF_AUX2='!QPF_AUX2!', QPF_AUX3='!QPF_AUX3!', QPF_PUBLISHED='!QPF_PUBLISHED!', QPF_ATTACHMENT='!QPF_ATTACHMENT!', QPF_UNIQID='!QPF_UNIQID!', QPF_SORT='!QPF_SORT!', QPF_MODIFYDATETIME='!QPF_MODIFYDATETIME!', QPF_MODIFYUSERNAME='!QPF_MODIFYUSERNAME!' WHERE QPF_ID='!QPF_ID!'";

	$qr_qp_updateFolderBookAttachment = "UPDATE QPFOLDER SET QPF_ATTACHMENT='!QPF_ATTACHMENT!' WHERE QPF_ID='!QPF_ID!'";

	$qr_qp_updateSortPage = "UPDATE QPFOLDER SET  QPF_SORT='!QPF_SORT!' WHERE QPF_ID='!QPF_ID!'";

	$qr_qp_updatePublishPage = "UPDATE QPFOLDER SET QPF_PUBLISHED='!QPF_PUBLISHED!' WHERE QPF_ID='!QPF_ID!'";

	$qr_qp_updatePublishBook = "UPDATE QPBOOK SET QPB_PUBLISHED='!QPB_PUBLISHED!', QPB_THEME='!QPB_THEME!' WHERE QPB_ID='!QPB_ID!'";

	$qr_qp_tree_selectFolders = "SELECT DF.QPF_ID, DF.QPB_ID, DF.QPF_TEXTID, DF.QPF_NAME, DF.QPF_TITLE, DF.QPF_PUBLISHED, DF.QPF_MODIFYDATETIME, DF.QPF_MODIFYUSERNAME, DF.QPF_ID_PARENT, DF.QPF_STATUS, DF.QPF_SORT, DF.QPF_UNIQID, 2147483647 AS USER_RIGHTS FROM TREE_FOLDER_TABLE DF WHERE QPB_ID='!QPB_ID!' ORDER BY DF.QPF_SORT, DF.FOLDER_NAME_FIELD";

	$qr_qp_ptree_selectFolders = "SELECT DF.* FROM TREE_FOLDER_TABLE DF WHERE FOLDER_PARENT_FIELD='!FOLDER_PARENT_FIELD!' ORDER BY DF.FOLDER_NAME_FIELD";

	$qr_qp_public_selectFolders = "SELECT DF.QPF_ID, DF.QPB_ID, DF.QPF_TEXTID, DF.QPF_NAME, DF.QPF_TITLE, DF.QPF_PUBLISHED, DF.QPF_MODIFYDATETIME, DF.QPF_MODIFYUSERNAME, DF.QPF_ID_PARENT, DF.QPF_STATUS, DF.QPF_SORT, DF.QPF_UNIQID FROM TREE_FOLDER_TABLE DF WHERE DF.QPB_ID='!QPB_ID!' AND DF.QPF_PUBLISHED='1' ORDER BY DF.QPF_SORT, DF.FOLDER_NAME_FIELD";

	$qr_qp_public_selectFolder = "SELECT * FROM TREE_FOLDER_TABLE WHERE FOLDER_ID_FIELD='!FOLDER_ID_FIELD!' AND QPB_ID='!QPB_ID!' AND QPF_PUBLISHED='1'";

	$qr_qp_selectedPublicNotes = "SELECT * FROM QPFOLDER WHERE %s AND QPB_ID='!QPB_ID!' AND QPF_PUBLISHED='1'";

	$qr_qp_searchPublicPages = "SELECT * FROM QPFOLDER WHERE QPB_ID='!QPB_ID!' AND QPF_PUBLISHED=1 AND ((%s) OR (%s)) ORDER BY QPB_ID, QPF_SORT";

	$qr_qp_searchPages = "SELECT * FROM QPFOLDER WHERE QPB_ID='!QPB_ID!' AND ((%s) OR (%s)) ORDER BY QPB_ID, QPF_SORT";

	$qr_qp_searchUniqId = "SELECT * FROM QPFOLDER WHERE QPB_ID='!QPB_ID!' AND QPF_UNIQID='!QPF_UNIQID!'";

	$qr_qp_checkTextIdBook = "SELECT COUNT(*) FROM QPBOOK WHERE QPB_TEXTID='!QPB_TEXTID!' AND QPB_ID<>'!QPB_ID!'";

	$qr_qp_checkTextIdPages = "SELECT COUNT(*) FROM QPFOLDER WHERE QPF_TEXTID='!QPF_TEXTID!' AND QPB_ID='!QPB_ID!' AND QPF_ID<>'!QPF_ID!'";

	$qr_qp_BookIdOnTxtId = "SELECT QPB_ID FROM QPBOOK WHERE QPB_TEXTID='!QPB_TEXTID!'";

	$qr_qp_PageIdOnTxtId = "SELECT QPF_ID FROM QPFOLDER WHERE QPF_TEXTID='!QPF_TEXTID!' AND QPB_ID='!QPB_ID!'";

	$qr_qp_getBookLastModifiedDate = "SELECT MAX( QPF_MODIFYDATETIME ) FROM QPFOLDER WHERE QPB_ID='!QPB_ID!'";

	$qr_qp_getPageLastModifiedDate = "SELECT QPF_MODIFYDATETIME FROM QPFOLDER WHERE QPB_ID='!QPB_ID!' AND QPF_ID='!QPF_ID!'";

	$qr_qp_getAllThemesList = "SELECT * FROM QPTHEMES ORDER BY QPT_NAME";

	$qr_qp_getApplicableThemesList = "SELECT * FROM QPTHEMES WHERE QPT_SHARED=1 ORDER BY QPT_NAME";

	$qr_qp_getTheme = "SELECT * FROM QPTHEMES WHERE QPT_ID='!QPT_ID!'";

	$qr_qp_getSharedTheme = "SELECT * FROM QPTHEMES WHERE QPT_ID='!QPT_ID!' AND QPT_SHARED=1";

	$qr_qp_updateThemeShare = "UPDATE QPTHEMES SET QPT_SHARED='!QPT_SHARED!' WHERE QPT_ID='!QPT_ID!'";

	$qr_qp_deleteTheme = "DELETE FROM QPTHEMES WHERE QPT_ID='!QPT_ID!'";

	$qr_qp_addTheme = "INSERT INTO QPTHEMES ( QPT_NAME, QPT_TYPE, QPT_SHARED, QPT_HEADER, QPT_PROPERTIES, QPT_USERID, QPT_ATTACHMENT, QPT_UNIQID ) VALUES ( '!QPT_NAME!', '!QPT_TYPE!', '!QPT_SHARED!', '!QPT_HEADER!', '!QPT_PROPERTIES!', '!QPT_USERID!', '!QPT_ATTACHMENT!', '!QPT_UNIQID!' )";

	$qr_qp_modTheme = "UPDATE QPTHEMES  SET QPT_NAME='!QPT_NAME!', QPT_TYPE='!QPT_TYPE!', QPT_SHARED='!QPT_SHARED!', QPT_HEADER='!QPT_HEADER!', QPT_PROPERTIES='!QPT_PROPERTIES!', QPT_ATTACHMENT='!QPT_ATTACHMENT!', QPT_UNIQID='!QPT_UNIQID!' WHERE QPT_ID='!QPT_ID!'";

	$qr_qp_modThemeTopData = "UPDATE QPTHEMES SET QPT_HEADER='!QPT_HEADER!', QPT_ATTACHMENT='!QPT_ATTACHMENT!', QPT_UNIQID='!QPT_UNIQID!' WHERE QPT_ID='!QPT_ID!'";

	$qr_qp_updateThemeAttachment = "UPDATE QPTHEMES SET QPT_ATTACHMENT='!QPT_ATTACHMENT!' WHERE QPT_ID='!QPT_ID!'";

	$qr_qp_getCountOfAppliedThemes = "SELECT QPB_THEME, COUNT(*) AS CNT FROM QPBOOK GROUP BY QPB_THEME";

	$qr_qp_updateBookThemes = "UPDATE QPBOOK SET QPB_THEME='!NEW_THEME!' WHERE QPB_THEME='!OLD_THEME!'";

	$qr_qp_checkThemeName = "SELECT COUNT(*) FROM QPTHEMES WHERE QPT_NAME='!QPT_NAME!'";

	$qr_qp_checkThemeNameExist = "SELECT COUNT(*) FROM QPTHEMES WHERE QPT_NAME='!QPT_NAME!' AND QPT_ID<>'!QPT_ID!'";
?>