<?php

	//
	// Document Depot queries
	//
	global $qr_pd_maxSort;
	$qr_pd_maxSort = "SELECT MAX(PL_SORT) FROM PIXLIST WHERE PF_ID='!PF_ID!'";

	global $qr_pd_insertFile;
	$qr_pd_insertFile = "INSERT INTO PIXLIST (PL_ID, PF_ID, PL_DESC, PL_FILENAME, PL_FILETYPE, PL_FILESIZE, PL_UPLOADDATETIME, PL_UPLOADUSERNAME, PL_MIMETYPE, PL_DISKFILENAME, PL_STATUSINT, PL_MODIFYDATETIME, PL_MODIFYUSERNAME, PL_SORT ) VALUES ('!PL_ID!', '!PF_ID!', '!PL_DESC!', '!PL_FILENAME!', '!PL_FILETYPE!', '!PL_FILESIZE!', NOW(), '!PL_UPLOADUSERNAME!', '!PL_MIMETYPE!', '!PL_DISKFILENAME!', '!PL_STATUSINT!', NOW(), '!PL_UPLOADUSERNAME!', '!PL_SORT!' )";

	global $qr_pd_updateFile;
	$qr_pd_updateFile = "UPDATE PIXLIST SET PL_VERSIONCOMMENT='!PL_VERSIONCOMMENT!', PL_FILENAME='!PL_FILENAME!', PL_FILESIZE='!PL_FILESIZE!', PL_MIMETYPE='!PL_MIMETYPE!', PL_DISKFILENAME='!PL_DISKFILENAME!', PL_STATUSINT='!PL_STATUSINT!', PL_MODIFYDATETIME=NOW(), PL_MODIFYUSERNAME='!PL_MODIFYUSERNAME!', PL_CHECKSTATUS='!PL_CHECKSTATUS!', PL_CHECKUSERID='!PL_CHECKUSERID!', PL_CHECKDATETIME=NOW() WHERE PL_ID='!PL_ID!'";
	
	global $qr_pd_updateFileTitleAndDescr;
	$qr_pd_updateFileTitleAndDescr = "UPDATE PIXLIST SET PL_FILENAME='!PL_FILENAME!', PL_DESC='!PL_DESC!', PL_MODIFYDATETIME=NOW(), PL_MODIFYUSERNAME='!PL_MODIFYUSERNAME!', PL_DISKFILENAME='!PL_DISKFILENAME!' WHERE PL_ID='!PL_ID!'";
	
	global $qr_pd_updateFileDescr;
	$qr_pd_updateFileDescr = "UPDATE PIXLIST SET PL_DESC='!PL_DESC!', PL_MODIFYDATETIME=NOW(), PL_MODIFYUSERNAME='!PL_MODIFYUSERNAME!' WHERE PL_ID='!PL_ID!'";

	global $qr_pd_getMaxPL_ID;
	$qr_pd_getMaxPL_ID = "SELECT MAX(PL_ID) FROM PIXLIST";

	global $qr_pd_selectFile;
	$qr_pd_selectFile = "SELECT * FROM PIXLIST WHERE PL_ID='!PL_ID!'";

	global $qr_pd_updateFileCheckStatus;
	$qr_pd_updateFileCheckStatus = "UPDATE PIXLIST SET PL_CHECKUSERID='!PL_CHECKUSERID!', PL_CHECKDATETIME=NOW(), PL_CHECKSTATUS='!PL_CHECKSTATUS!' WHERE PL_ID='!PL_ID!'";

	global $qr_pd_updateFileStatus;
	$qr_pd_updateFileStatus = "UPDATE PIXLIST SET PL_STATUSINT='!PL_STATUSINT!', PL_DISKFILENAME='!PL_DISKFILENAME!' WHERE PL_ID='!PL_ID!'";

	global $qr_pd_updateFileLocationStatus;
	$qr_pd_updateFileLocationStatus = "UPDATE PIXLIST SET PL_STATUSINT='!PL_STATUSINT!', PL_DISKFILENAME='!PL_DISKFILENAME!', PF_ID='!PF_ID!', PL_DELETE_U_ID='!PL_DELETE_U_ID!', PL_DELETE_DATETIME='!PL_DELETE_DATETIME!', PL_DELETE_USERNAME='!PL_DELETE_USERNAME!' WHERE PL_ID='!PL_ID!'";

	global $qr_pd_deleteFile;
	$qr_pd_deleteFile = "DELETE FROM PIXLIST WHERE PL_ID='!PL_ID!'";

	global $qr_pd_updateFileLocation;
	$qr_pd_updateFileLocation = "UPDATE PIXLIST SET PL_DISKFILENAME='!PL_DISKFILENAME!', PF_ID='!PF_ID!', PL_SORT='!PL_SORT!' WHERE PL_ID='!PL_ID!'";

	global $qr_pd_updateFileNameDescription;
	$qr_pd_updateFileNameDescription = "UPDATE PIXLIST SET PL_FILENAME='!PL_FILENAME!', PL_DESC='!PL_DESC!'  WHERE PL_ID='!PL_ID!'";

	global $qr_pd_updateFileName;
	$qr_pd_updateFileName = "UPDATE PIXLIST SET PL_FILENAME='!PL_FILENAME!' WHERE PL_ID='!PL_ID!'";

	global $qr_pd_transferFilesToSystem;
	$qr_pd_transferFilesToSystem = "UPDATE PIXLIST SET PL_OWNER_U_ID='\$SYSTEM' WHERE PL_OWNER_U_ID='!U_ID!'";

	global $qr_pd_totalRights;
	$qr_pd_totalRights = "(SELECT
							IF ( UA.AR_VALUE IS NULL, 0, UA.AR_VALUE ) |
							IF ( (SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
							AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) IS NULL, 0,
							(SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
							AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) )
							FROM U_ACCESSRIGHTS AS UA WHERE AR_ID='!U_ID!' AND AR_PATH='/ROOT/PD/FOLDERS' AND AR_OBJECT_ID=PF.PF_ID)";

	global $qr_pd_findFiles;
	$qr_pd_findFiles = "SELECT PL.*, PF.PF_NAME, $qr_pd_totalRights AS TREE_ACCESS_RIGHTS FROM PIXLIST PL, PIXFOLDER PF WHERE ((%s) OR (%s)) AND PF.PF_ID=PL.PF_ID AND PL_STATUSINT=0 HAVING TREE_ACCESS_RIGHTS > 0 ORDER BY %s";

	global $qr_pd_findFilesGlobal;
	$qr_pd_findFilesGlobal = "SELECT PL.*, PF.PF_NAME, 7 AS TREE_ACCESS_RIGHTS FROM PIXLIST PL, PIXFOLDER PF WHERE ((%s) OR (%s)) AND PF.PF_ID=PL.PF_ID AND PL_STATUSINT=0 ORDER BY %s";

	global $qr_pd_findGroupFiles;
	$qr_pd_findGroupFiles = "SELECT PL.*, PF.PF_NAME, MAX(PFGA.DA_RIGHT) AS DA_RIGHT FROM DOCGROUPACCESS PFGA, UGROUP_USER UGU, PIXLIST PL, PIXFOLDER PF WHERE (%s OR %s) AND PL.PF_ID = PFGA.PF_ID AND PFGA.UG_ID = UGU.UG_ID AND UGU.U_ID = '!U_ID!' AND PF.PF_ID=PL.PF_ID GROUP BY PL.PL_ID ORDER BY %s";

	global $qr_pd_updateFolderStatus;
	$qr_pd_updateFolderStatus = "UPDATE PIXFOLDER SET PF_STATUS='!PF_STATUS!' WHERE PF_ID='!PF_ID!'";

	global $qr_pd_updateFolderCreateStatusFields;
	$qr_pd_updateFolderCreateStatusFields = "UPDATE PIXFOLDER SET PF_CREATEDATETIME=now(), PF_CREATEUSERNAME='!PF_CREATEUSERNAME!', PF_MODIFYDATETIME=now(), PF_MODIFYUSERNAME='!PF_MODIFYUSERNAME!' WHERE PF_ID='!PF_ID!'";

	global $qr_pd_updateFolderCreateMoveStatusFields;
	$qr_pd_updateFolderCreateMoveStatusFields = "UPDATE PIXFOLDER SET PF_CREATEDATETIME='!PF_CREATEDATETIME!', PF_CREATEUSERNAME='!PF_CREATEUSERNAME!', PF_MODIFYDATETIME=now(), PF_MODIFYUSERNAME='!PF_MODIFYUSERNAME!' WHERE PF_ID='!PF_ID!'";

	global $qr_pd_updateFodlerUpdateStatusFields;
	$qr_pd_updateFodlerUpdateStatusFields = "UPDATE PIXFOLDER SET PF_MODIFYDATETIME=now(), PF_MODIFYUSERNAME='!PF_MODIFYUSERNAME!' WHERE PF_ID='!PF_ID!'";

	global $qr_pd_selectUsersContacts;
	$qr_pd_selectUsersContacts = "SELECT C.* FROM CONTACT C, WBS_USER U WHERE C_EMAILADDRESS IS NOT NULL AND C.CF_ID=\"1.\" AND U.C_ID=C.C_ID AND U.U_STATUS <> 1 ORDER  BY UPPER(CONCAT(IF(C_FIRSTNAME is not null, C_FIRSTNAME, ''), IF(C_MIDDLENAME is not null, C_MIDDLENAME, ''), IF(C_LASTNAME is not null, C_LASTNAME, ''), IF(C_NICKNAME is not null, C_NICKNAME, ''), IF(C_EMAILADDRESS is not null, C_EMAILADDRESS, '')))";

	global $qr_pd_selectContactEmail;
	$qr_pd_selectContactEmail = "SELECT C_EMAILADDRESS FROM CONTACT WHERE C_ID='!C_ID!'";

	global $qr_pd_imageNum;
	$qr_pd_imageNum = "SELECT COUNT(*) FROM PIXLIST WHERE INSTR(LOWER(PL_FILENAME),'.jpg') OR INSTR(LOWER(PL_FILENAME),'.gif') OR INSTR(LOWER(PL_FILENAME),'.png')";

	global $qr_pd_selectFileByName;
	$qr_pd_selectFileByName = "SELECT * FROM PIXLIST WHERE UPPER(TRIM(PL_FILENAME))=UPPER(TRIM('!PL_FILENAME!')) AND PF_ID='!PF_ID!' AND PL_STATUSINT=0";

	global $qr_pd_selectMaxHistoryID;
	$qr_pd_selectMaxHistoryID = "SELECT MAX(PLH_VERSION) FROM PIXLISTHISTORY WHERE PL_ID='!PL_ID!'";

	global $qr_pd_insertHistory;
	$qr_pd_insertHistory = "INSERT INTO PIXLISTHISTORY(PL_ID, PLH_VERSION, PLH_DATETIME, PLH_USERNAME, PLH_DISKFILENAME, PLH_DESC, PLH_SIZE) VALUES ('!PL_ID!', '!PLH_VERSION!', NOW(), '!PLH_USERNAME!', '!PLH_DISKFILENAME!', '!PLH_DESC!', '!PLH_SIZE!')";

	global $qr_pd_selectFileHistory;
	$qr_pd_selectFileHistory = "SELECT * FROM PIXLISTHISTORY WHERE PL_ID='!PL_ID!' ORDER BY PLH_DATETIME ASC";

	global $qr_pd_deleteFileHistory;
	$qr_pd_deleteFileHistory = "DELETE FROM PIXLISTHISTORY WHERE PL_ID='!PL_ID!'";

	global $qr_pd_selectFolderFilesHistory;
	$qr_pd_selectFolderFilesHistory = "SELECT DH.*, PL.PL_OWNER_U_ID FROM PIXLISTHISTORY DH, PIXLIST PL WHERE DH.PL_ID=PL.PL_ID AND PL.PF_ID='!PF_ID!'";

	global $qr_pd_selectHistoryRecord;
	$qr_pd_selectHistoryRecord = "SELECT PLH.*, PL_OWNER_U_ID FROM PIXLISTHISTORY PLH, PIXLIST PL WHERE PLH.PL_ID='!PL_ID!' AND PL.PL_ID=PLH.PL_ID AND PLH_VERSION='!PLH_VERSION!'";

	global $qr_pd_selectDuplicateFilenames;
	$qr_pd_selectDuplicateFilenames = "SELECT PF.PF_ID, PF.PL_FILENAME, UPPER(TRIM(PF.PL_FILENAME)) AS PL_FILENAME FROM PIXLIST PF, PIXFOLDER PFL WHERE PFL.PF_ID=PF.PF_ID AND PF.PL_STATUSINT <> -1 GROUP BY PF.PF_ID, UPPER(TRIM(PF.PL_FILENAME)) HAVING COUNT(*) > 1 ORDER BY PFL.PF_ID, PFL.PF_NAME";

	global $qr_pd_selectFileNameCount;
	$qr_pd_selectFileNameCount = "SELECT COUNT(*) FROM PIXLIST WHERE UPPER(TRIM(PL_FILENAME))=UPPER(TRIM('!PL_FILENAME!')) AND PF_ID='!PF_ID!' AND PL_ID <> '!PL_ID!' AND PL_STATUSINT=0";

	global $qr_pd_selectFolderFiles;
	$qr_pd_selectFolderFiles = "SELECT * FROM PIXLIST WHERE PF_ID='!PF_ID!'";

	global $qr_pd_selectOldFileVersions;
	$qr_pd_selectOldFileVersions = "SELECT PLH.PL_ID, PLH_VERSION, PLH_SIZE, PLH_DISKFILENAME, PL.PL_OWNER_U_ID FROM PIXLISTHISTORY PLH, PIXLIST PL WHERE PLH.PL_ID='!PL_ID!' AND PL.PL_ID=PLH.PL_ID ORDER BY PLH_VERSION DESC LIMIT %s, 10000000";

	global $qr_pd_deleteFileVersion;
	$qr_pd_deleteFileVersion = "DELETE FROM PIXLISTHISTORY WHERE PL_ID='!PL_ID!' AND PLH_VERSION='!PLH_VERSION!'";

	global $qr_pd_selectFileName;
	$qr_pd_selectFileName = "SELECT PL_FILENAME FROM PIXLIST WHERE PL_ID='!PL_ID!'";

	global $qr_pd_selectFilesForSort;
	$qr_pd_selectFilesForSort = "SELECT * FROM PIXLIST WHERE PL_ID<='!MAX!' AND PL_ID>='!MIN!' AND PF_ID='!PF_ID!' AND PL_STATUSINT=0 ORDER BY PL_ID";

	global $qr_pd_updateSort;
	$qr_pd_updateSort = "UPDATE PIXLIST SET PL_SORT='!PL_SORT!' WHERE PL_ID='!PL_ID!'";

	//
	// Reports queries
	//

	$qr_pd_selectUserNameChunk = "CONCAT( IF (C.C_FIRSTNAME IS NOT NULL, CONCAT(C.C_FIRSTNAME, \" \"), \"\"), IF ( C.C_MIDDLENAME IS NOT NULL AND C.C_MIDDLENAME <> \"\", CONCAT(SUBSTRING(C.C_MIDDLENAME, 1, 1), \". \"), \"\" ), IF (C.C_LASTNAME IS NOT NULL, CONCAT(C.C_LASTNAME, \" \"), \"\") ) AS USERNAME";

	$qr_pd_selectStorageByUser = "SELECT DU.*, UDQ.UDQ_SIZE*1024 AS UDQ_SIZE, IF ( UDQ.UDQ_SIZE IS NOT NULL, DU_SIZE/(UDQ.UDQ_SIZE*1024)*100, '' ) as RATIO, %s FROM (DISK_USAGE DU, WBS_USER U, CONTACT C) LEFT JOIN USER_DISK_QUOTA UDQ ON UDQ.UDQ_USER_ID=DU.DU_USER_ID WHERE DU_APP_ID='DD' AND U.U_ID = DU.DU_USER_ID AND C.C_ID=U.C_ID ORDER BY DU.DU_SIZE DESC";

	$qr_pd_selectFileTypeStats ="SELECT UPPER(PL_FILETYPE) AS PL_FILETYPE, SUM(PL_FILESIZE) AS SIZE, COUNT(*) AS CNT FROM PIXLIST GROUP BY PL_FILETYPE ORDER BY 1 ASC";

	$qr_pd_selectRecentFilesByDate = "SELECT PL_FILENAME, PL_FILESIZE, PL_UPLOADDATETIME, PL_UPLOADUSERNAME FROM PIXLIST WHERE PL_UPLOADDATETIME > ( DATE_SUB(NOW(), INTERVAL %s DAY) ) ORDER BY 3 DESC";

	$qr_pd_selectRecentFilesByDateRange = "SELECT PL_FILENAME, PL_FILESIZE, PL_UPLOADDATETIME, PL_UPLOADUSERNAME FROM PIXLIST WHERE PL_UPLOADDATETIME >= '%s' AND PL_UPLOADDATETIME <= '%s' ORDER BY 3 DESC";

	$qr_pd_selectFolderSummaryStats = "SELECT PF.PF_ID, PF.PF_NAME, PF.PF_ID_PARENT, COUNT(PL_ID) AS CNT, SUM(PL_FILESIZE) AS SIZE FROM (PIXFOLDER PF) LEFT JOIN PIXLIST PL ON PL.PF_ID=PF.PF_ID WHERE PF.PF_STATUS=0 GROUP BY PF.PF_ID ORDER BY PF.PF_NAME";

	$qr_pd_selectFreqFilesStatsByDate = "SELECT DISTINCT(PL.PL_ID), PL_FILENAME, PL_UPLOADUSERNAME, COUNT(DISTINCT(PLH2.PLH_VERSION)) AS CNT FROM (PIXLIST PL, PIXLISTHISTORY PLH) LEFT JOIN PIXLISTHISTORY PLH2 ON PLH2.PL_ID=PL.PL_ID WHERE PLH.PL_ID=PL.PL_ID AND (PL_UPLOADDATETIME > ( DATE_SUB( NOW( ) , INTERVAL %s DAY ) ) OR PLH.PLH_DATETIME > ( DATE_SUB( NOW( ) , INTERVAL %s DAY ) ) ) GROUP BY PL.PL_ID ORDER BY 4 DESC";

	$qr_pd_selectFreqFilesStatsByDateRange = "SELECT DISTINCT(PL.PL_ID), PL_FILENAME, PL_UPLOADUSERNAME, COUNT(DISTINCT(PLH2.PLH_VERSION)) AS CNT FROM (PIXLIST PL, PIXLISTHISTORY PLH) LEFT JOIN PIXLISTHISTORY PLH2 ON PLH2.PL_ID=PL.PL_ID WHERE PLH.PL_ID=PL.PL_ID AND ( (PL_UPLOADDATETIME >= '%s' AND PL_UPLOADDATETIME <= '%s') OR (PLH.PLH_DATETIME >= '%s' AND PLH.PLH_DATETIME <= '%s') ) GROUP BY PL.PL_ID ORDER BY 4 DESC";
	
	// Share templated queries
	$qr_pd_selectSharedTemplates = "SELECT * FROM SHARED_TEMPLATES WHERE T_USER='!U_ID!' OR T_USER = '' ORDER BY T_ID";
	$qr_pd_selectSharedTemplate = "SELECT * FROM SHARED_TEMPLATES WHERE T_ID='!T_ID!' AND (T_USER='!U_ID!' OR T_USER = '')";
	
	// Other
	//$qr_pd_getImageById = "SELECT PL.*, PF.PF_NAME, $qr_pd_totalRights AS TREE_ACCESS_RIGHTS FROM PIXLIST PL, PIXFOLDER PF WHERE PL.PL_ID='!PL_ID!' AND PF.PF_ID=PL.PF_ID AND PL_STATUSINT=0 HAVING TREE_ACCESS_RIGHTS > 0";
	
	global $qr_pd_getFilesByIds;
	$qr_pd_getFilesByIds = "SELECT PL.*, PF.PF_NAME, $qr_pd_totalRights AS TREE_ACCESS_RIGHTS FROM PIXLIST PL, PIXFOLDER PF WHERE PL.PL_ID IN (%s) AND PF.PF_ID=PL.PF_ID AND PL_STATUSINT=0 HAVING TREE_ACCESS_RIGHTS > 0 %s";
	
	global $qr_pd_checkIsExistTitle;
	$qr_pd_checkIsExistTitle = "SELECT PL_ID FROM PIXLIST WHERE PF_ID='!PF_ID!' AND PL_FILENAME='!PL_FILENAME!' AND PL_ID <> '!PL_ID!'";
	
	
	global $qr_pd_updateFolderWidgets;
	$qr_pd_updateFolderWidgets = "UPDATE WG_PARAM SET WGP_VALUE='!NEW_FOLDER_ID!' WHERE WGP_VALUE='!OLD_FOLDER_ID!' AND WGP_NAME='FOLDERS' AND WG_ID IN (SELECT WG_ID FROM WG_WIDGET WHERE WT_ID='PDList')";

?>