<?php

	//
	// Document Depot queries
	//

	global $qr_dd_updateUploadedFile;
	$qr_dd_updateUploadedFile = "UPDATE DOCLIST SET `DL_FILESIZE` = '!DL_FILESIZE!' WHERE `DL_ID` = '!DL_ID!'";

	global $qr_dd_insertFile;
	$qr_dd_insertFile = "INSERT INTO DOCLIST(DL_ID, DF_ID, DL_DESC, DL_FILENAME, DL_FILETYPE, DL_FILESIZE, DL_UPLOADDATETIME, DL_UPLOADUSERNAME, DL_MIMETYPE, DL_DISKFILENAME, DL_STATUSINT, DL_MODIFYDATETIME, DL_MODIFYUSERNAME, DL_CHECKSTATUS, DL_CHECKUSERID, DL_CHECKDATETIME, DL_OWNER_U_ID) VALUES ('!DL_ID!', '!DF_ID!', '!DL_DESC!', '!DL_FILENAME!', '!DL_FILETYPE!', '!DL_FILESIZE!', NOW(), '!DL_UPLOADUSERNAME!', '!DL_MIMETYPE!', '!DL_DISKFILENAME!', '!DL_STATUSINT!', NOW(), '!DL_UPLOADUSERNAME!', '!DL_CHECKSTATUS!', '!DL_CHECKUSERID!', NOW(), '!DL_OWNER_U_ID!')";
	
	global $qr_dd_getv;
	$qr_dd_getv = "SELECT DL_ID, MAX( DLH_VERSION ) as MAX FROM `DOCLISTHISTORY` WHERE `DL_ID` IN (!FILES_ID!) GROUP BY DL_ID";
	
	global $qr_dd_updateFile;
	$qr_dd_updateFile = "UPDATE DOCLIST SET DL_VERSIONCOMMENT='!DL_VERSIONCOMMENT!', DL_FILENAME='!DL_FILENAME!', DL_FILESIZE='!DL_FILESIZE!', DL_MIMETYPE='!DL_MIMETYPE!', DL_DISKFILENAME='!DL_DISKFILENAME!', DL_STATUSINT='!DL_STATUSINT!', DL_MODIFYDATETIME=NOW(), DL_MODIFYUSERNAME='!DL_MODIFYUSERNAME!', DL_CHECKSTATUS='!DL_CHECKSTATUS!', DL_CHECKUSERID='!DL_CHECKUSERID!', DL_CHECKDATETIME=NOW() WHERE DL_ID='!DL_ID!'";

	global $qr_dd_getMaxDL_ID;
	$qr_dd_getMaxDL_ID = "SELECT MAX(DL_ID) FROM DOCLIST";

	global $qr_dd_selectFile;
	$qr_dd_selectFile = "SELECT * FROM DOCLIST WHERE DL_ID='!DL_ID!'";
	
	global $qr_dd_selectFileBySlug;
	$qr_dd_selectFileBySlug = "SELECT * FROM DOCLIST WHERE DL_LINK_SLUG='!DL_LINK_SLUG!'";
	
	global $qr_pd_updateFileDescr;
	$qr_pd_updateFileDescr = "UPDATE DOCLIST SET DL_DESC='!DL_DESC!', DL_MODIFYDATETIME=NOW(), DL_MODIFYUSERNAME='!DL_MODIFYUSERNAME!' WHERE DL_ID='!DL_ID!'";

	global $qr_dd_updateFileCheckStatus;
	$qr_dd_updateFileCheckStatus = "UPDATE DOCLIST SET DL_CHECKUSERID='!DL_CHECKUSERID!', DL_CHECKDATETIME=NOW(), DL_CHECKSTATUS='!DL_CHECKSTATUS!' WHERE DL_ID='!DL_ID!'";

	global $qr_dd_updateFileStatus;
	$qr_dd_updateFileStatus = "UPDATE DOCLIST SET DL_STATUSINT='!DL_STATUSINT!', DL_DISKFILENAME='!DL_DISKFILENAME!' WHERE DL_ID='!DL_ID!'";

	global $qr_dd_updateFileLocationStatus;
	$qr_dd_updateFileLocationStatus = "UPDATE DOCLIST SET DL_STATUSINT='!DL_STATUSINT!', DL_DISKFILENAME='!DL_DISKFILENAME!', DF_ID='!DF_ID!', DL_DELETE_U_ID='!DL_DELETE_U_ID!', DL_DELETE_DATETIME='!DL_DELETE_DATETIME!', DL_DELETE_USERNAME='!DL_DELETE_USERNAME!' WHERE DL_ID='!DL_ID!'";

	global $qr_dd_deleteFile;
	$qr_dd_deleteFile = "DELETE FROM DOCLIST WHERE DL_ID='!DL_ID!'";

	global $qr_dd_updateFileLocation;
	$qr_dd_updateFileLocation = "UPDATE DOCLIST SET DL_DISKFILENAME='!DL_DISKFILENAME!', DF_ID='!DF_ID!' WHERE DL_ID='!DL_ID!'";

	global $qr_dd_updateFileNameDescription;
	$qr_dd_updateFileNameDescription = "UPDATE DOCLIST SET DL_FILENAME='!DL_FILENAME!', DL_DESC='!DL_DESC!'  WHERE DL_ID='!DL_ID!'";

	global $qr_dd_updateFileName;
	$qr_dd_updateFileName = "UPDATE DOCLIST SET DL_FILENAME='!DL_FILENAME!' WHERE DL_ID='!DL_ID!'";

	global $qr_dd_deleteUserRights;
	$qr_dd_deleteUserRights = "DELETE FROM DOCACCESS WHERE U_ID='!U_ID!'";

	global $qr_dd_transferFilesToSystem;
	$qr_dd_transferFilesToSystem = "UPDATE DOCLIST SET DL_OWNER_U_ID='\$SYSTEM' WHERE DL_OWNER_U_ID='!U_ID!'";

	global $qr_dd_totalRights;
	$qr_dd_totalRights = "(SELECT
							IF ( UA.AR_VALUE IS NULL, 0, UA.AR_VALUE ) |
							IF ( (SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
							AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) IS NULL, 0,
							(SELECT BIT_OR( UG.AR_VALUE ) FROM UG_ACCESSRIGHTS AS UG, UGROUP_USER AS UGU WHERE UG.AR_ID=UGU.UG_ID
							AND UGU.U_ID=UA.AR_ID AND UA.AR_OBJECT_ID=UG.AR_OBJECT_ID AND UA.AR_PATH=UG.AR_PATH GROUP BY UGU.U_ID) )
							FROM U_ACCESSRIGHTS AS UA WHERE AR_ID='!U_ID!' AND AR_PATH='/ROOT/DD/FOLDERS' AND AR_OBJECT_ID=DF.DF_ID)";

	global $qr_dd_findFiles;
	$qr_dd_findFiles = "SELECT DL.*, DF.DF_NAME, $qr_dd_totalRights AS TREE_ACCESS_RIGHTS FROM DOCLIST DL, DOCFOLDER DF WHERE ((%s) OR (%s)) AND DF.DF_ID=DL.DF_ID AND DL_STATUSINT=0 HAVING TREE_ACCESS_RIGHTS > 0 ORDER BY %s";

	global $qr_dd_findFilesGlobal;
	$qr_dd_findFilesGlobal = "SELECT DL.*, DF.DF_NAME, 7 AS TREE_ACCESS_RIGHTS FROM DOCLIST DL, DOCFOLDER DF WHERE ((%s) OR (%s)) AND DF.DF_ID=DL.DF_ID AND DL_STATUSINT=0 ORDER BY %s";

	global $qr_dd_findGroupFiles;
	$qr_dd_findGroupFiles = "SELECT DL.*, DF.DF_NAME, MAX(DFGA.DA_RIGHT) AS DA_RIGHT FROM DOCGROUPACCESS DFGA, UGROUP_USER UGU, DOCLIST DL, DOCFOLDER DF WHERE (%s OR %s) AND DL.DF_ID = DFGA.DF_ID AND DFGA.UG_ID = UGU.UG_ID AND UGU.U_ID = '!U_ID!' AND DF.DF_ID=DL.DF_ID GROUP BY DL.DL_ID ORDER BY %s";

	global $qr_dd_updateFolderStatus;
	$qr_dd_updateFolderStatus = "UPDATE DOCFOLDER SET DF_STATUS='!DF_STATUS!' WHERE DF_ID='!DF_ID!'";

	global $qr_dd_updateFolderCreateStatusFields;
	//$qr_dd_updateFolderCreateStatusFields = "UPDATE DOCFOLDER SET DF_CREATEDATETIME=now(), DF_CREATEUSERNAME='!DF_CREATEUSERNAME!', DF_MODIFYDATETIME=now(), DF_MODIFYUSERNAME='!DF_MODIFYUSERNAME!', DF_SPECIALSTATUS='!DF_SPECIALSTATUS!' WHERE DF_ID='!DF_ID!'";
	$qr_dd_updateFolderCreateStatusFields = "UPDATE DOCFOLDER SET DF_CREATEDATETIME=now(), DF_CREATEUSERNAME='!DF_CREATEUSERNAME!', DF_MODIFYDATETIME=now(), DF_MODIFYUSERNAME='!DF_MODIFYUSERNAME!' WHERE DF_ID='!DF_ID!'";

	global $qr_dd_updateFolderCreateMoveStatusFields;
	//$qr_dd_updateFolderCreateMoveStatusFields = "UPDATE DOCFOLDER SET DF_CREATEDATETIME='!DF_CREATEDATETIME!', DF_CREATEUSERNAME='!DF_CREATEUSERNAME!', DF_MODIFYDATETIME=now(), DF_MODIFYUSERNAME='!DF_MODIFYUSERNAME!', DF_SPECIALSTATUS='!DF_SPECIALSTATUS!' WHERE DF_ID='!DF_ID!'";
	$qr_dd_updateFolderCreateMoveStatusFields = "UPDATE DOCFOLDER SET DF_CREATEDATETIME='!DF_CREATEDATETIME!', DF_CREATEUSERNAME='!DF_CREATEUSERNAME!', DF_MODIFYDATETIME=now(), DF_MODIFYUSERNAME='!DF_MODIFYUSERNAME!' WHERE DF_ID='!DF_ID!'";
	
	global $qr_dd_updateFolderSpecialstatusFields;
	$qr_dd_updateFolderSpecialstatusFields = "UPDATE DOCFOLDER SET DF_SPECIALSTATUS='!DF_SPECIALSTATUS!' WHERE DF_ID='!DF_ID!'";

	global $qr_dd_updateFodlerUpdateStatusFields;
	$qr_dd_updateFodlerUpdateStatusFields = "UPDATE DOCFOLDER SET DF_MODIFYDATETIME=now(), DF_MODIFYUSERNAME='!DF_MODIFYUSERNAME!' WHERE DF_ID='!DF_ID!'";

	global $qr_dd_selectUsersContacts;
	$qr_dd_selectUsersContacts = "SELECT C.* FROM CONTACT C, WBS_USER U WHERE C_EMAILADDRESS IS NOT NULL AND C.CF_ID=\"1.\" AND U.C_ID=C.C_ID AND U.U_STATUS <> 1 ORDER  BY UPPER(CONCAT(IF(C_FIRSTNAME is not null, C_FIRSTNAME, ''), IF(C_MIDDLENAME is not null, C_MIDDLENAME, ''), IF(C_LASTNAME is not null, C_LASTNAME, ''), IF(C_EMAILADDRESS is not null, C_EMAILADDRESS, '')))";

	global $qr_dd_selectContactEmail;
	$qr_dd_selectContactEmail = "SELECT C_EMAILADDRESS FROM CONTACT WHERE C_ID='!C_ID!'";

	global $qr_dd_imageNum;
	$qr_dd_imageNum = "SELECT COUNT(*) FROM DOCLIST WHERE INSTR(LOWER(DL_FILENAME),'.jpg') OR INSTR(LOWER(DL_FILENAME),'.gif') OR INSTR(LOWER(DL_FILENAME),'.png')";

	global $qr_dd_selectFileByName;
	$qr_dd_selectFileByName = "SELECT * FROM DOCLIST WHERE UPPER(TRIM(DL_FILENAME))=UPPER(TRIM('!DL_FILENAME!')) AND DF_ID='!DF_ID!' AND DL_STATUSINT=0";

	global $qr_dd_selectMaxHistoryID;
	$qr_dd_selectMaxHistoryID = "SELECT MAX(DLH_VERSION) FROM DOCLISTHISTORY WHERE DL_ID='!DL_ID!'";

	global $qr_dd_insertHistory;
	$qr_dd_insertHistory = "INSERT INTO DOCLISTHISTORY(DL_ID, DLH_VERSION, DLH_DATETIME, DLH_USERNAME, DLH_DISKFILENAME, DLH_DESC, DLH_SIZE) VALUES ('!DL_ID!', '!DLH_VERSION!', NOW(), '!DLH_USERNAME!', '!DLH_DISKFILENAME!', '!DLH_DESC!', '!DLH_SIZE!')";

	global $qr_dd_selectFileHistory;
	$qr_dd_selectFileHistory = "SELECT * FROM DOCLISTHISTORY WHERE DL_ID='!DL_ID!' ORDER BY DLH_DATETIME ASC";

	global $qr_dd_deleteFileHistory;
	$qr_dd_deleteFileHistory = "DELETE FROM DOCLISTHISTORY WHERE DL_ID='!DL_ID!'";

	global $qr_dd_selectFolderFilesHistory;
	$qr_dd_selectFolderFilesHistory = "SELECT DH.*, DL.DL_OWNER_U_ID FROM DOCLISTHISTORY DH, DOCLIST DL WHERE DH.DL_ID=DL.DL_ID AND DL.DF_ID='!DF_ID!'";

	global $qr_dd_selectHistoryRecord ;
	$qr_dd_selectHistoryRecord = "SELECT DLH.*, DL_OWNER_U_ID FROM DOCLISTHISTORY DLH, DOCLIST DL WHERE DLH.DL_ID='!DL_ID!' AND DL.DL_ID=DLH.DL_ID AND DLH_VERSION='!DLH_VERSION!'";

	global $qr_dd_selectDuplicateFilenames;
	$qr_dd_selectDuplicateFilenames = "SELECT DF.DF_ID, DF.DL_FILENAME, UPPER(TRIM(DF.DL_FILENAME)) AS DL_FILENAME FROM DOCLIST DF, DOCFOLDER DFL WHERE DFL.DF_ID=DF.DF_ID AND DF.DL_STATUSINT <> -1 GROUP BY DF.DF_ID, UPPER(TRIM(DF.DL_FILENAME)) HAVING COUNT(*) > 1 ORDER BY DFL.DF_ID, DFL.DF_NAME";

	global $qr_dd_selectFileNameCount;
	$qr_dd_selectFileNameCount = "SELECT COUNT(*) FROM DOCLIST WHERE UPPER(TRIM(DL_FILENAME))=UPPER(TRIM('!DL_FILENAME!')) AND DF_ID='!DF_ID!' AND DL_ID <> '!DL_ID!' AND DL_STATUSINT=0";

	
	global $qr_dd_selectFolderFiles;
	$qr_dd_selectFolderFiles = "SELECT * FROM DOCLIST WHERE DF_ID='!DF_ID!'";

	global $qr_dd_selectOldFileVersions;
	$qr_dd_selectOldFileVersions = "SELECT DLH.DL_ID, DLH_VERSION, DLH_SIZE, DLH_DISKFILENAME, DL.DL_OWNER_U_ID FROM DOCLISTHISTORY DLH, DOCLIST DL WHERE DLH.DL_ID='!DL_ID!' AND DL.DL_ID=DLH.DL_ID ORDER BY DLH_VERSION DESC LIMIT %s, 10000000";

	global $qr_dd_deleteFileVersion;
	$qr_dd_deleteFileVersion = "DELETE FROM DOCLISTHISTORY WHERE DL_ID='!DL_ID!' AND DLH_VERSION='!DLH_VERSION!'";

	global $qr_dd_selectFileName;
	$qr_dd_selectFileName = "SELECT DL_FILENAME FROM DOCLIST WHERE DL_ID='!DL_ID!'";
	
	global $qr_dd_updateFolderWidgets;
	$qr_dd_updateFolderWidgets = "UPDATE WG_PARAM SET WGP_VALUE='!NEW_FOLDER_ID!' WHERE WGP_VALUE='!OLD_FOLDER_ID!' AND (WGP_NAME='FOLDER' OR WGP_NAME='FOLDERS') AND WG_ID IN (SELECT WG_ID FROM WG_WIDGET WHERE WT_ID='DDList' OR WT_ID='DDUploader')";

	//
	// Reports queries
	//

	$qr_dd_selectUserNameChunk = "CONCAT( IF (C.C_FIRSTNAME IS NOT NULL, CONCAT(C.C_FIRSTNAME, \" \"), \"\"), IF ( C.C_MIDDLENAME IS NOT NULL AND C.C_MIDDLENAME <> \"\", CONCAT(SUBSTRING(C.C_MIDDLENAME, 1, 1), \". \"), \"\" ), IF (C.C_LASTNAME IS NOT NULL, CONCAT(C.C_LASTNAME, \" \"), \"\") ) AS USERNAME";

	$qr_dd_selectStorageByUser = "SELECT DU.*, UDQ.UDQ_SIZE*1024 AS UDQ_SIZE, IF ( UDQ.UDQ_SIZE IS NOT NULL, DU_SIZE/(UDQ.UDQ_SIZE*1024)*100, '' ) as RATIO, %s FROM (DISK_USAGE DU, WBS_USER U, CONTACT C) LEFT JOIN USER_DISK_QUOTA UDQ ON UDQ.UDQ_USER_ID=DU.DU_USER_ID WHERE DU_APP_ID='DD' AND U.U_ID = DU.DU_USER_ID AND C.C_ID=U.C_ID ORDER BY DU.DU_SIZE DESC";

	$qr_dd_selectFileTypeStats ="SELECT UPPER(DL_FILETYPE) AS DL_FILETYPE, SUM(DL_FILESIZE) AS SIZE, COUNT(*) AS CNT FROM DOCLIST GROUP BY DL_FILETYPE ORDER BY 1 ASC";

	$qr_dd_selectRecentFilesByDate = "SELECT DL_FILENAME, DL_FILESIZE, DL_UPLOADDATETIME, DL_UPLOADUSERNAME FROM DOCLIST WHERE DL_UPLOADDATETIME > ( DATE_SUB(NOW(), INTERVAL %s DAY) ) ORDER BY 3 DESC";

	$qr_dd_selectRecentFilesByDateRange = "SELECT DL_FILENAME, DL_FILESIZE, DL_UPLOADDATETIME, DL_UPLOADUSERNAME FROM DOCLIST WHERE DL_UPLOADDATETIME >= '%s' AND DL_UPLOADDATETIME <= '%s' ORDER BY 3 DESC";

	$qr_dd_selectFolderSummaryStats = "SELECT DF.DF_ID, DF.DF_NAME, DF.DF_ID_PARENT, COUNT(DL_ID) AS CNT, SUM(DL_FILESIZE) AS SIZE FROM (DOCFOLDER DF) LEFT JOIN DOCLIST DL ON DL.DF_ID=DF.DF_ID WHERE DF.DF_STATUS=0 GROUP BY DF.DF_ID ORDER BY DF.DF_NAME";

	$qr_dd_selectFreqFilesStatsByDate = "SELECT DISTINCT(DL.DL_ID), DL_FILENAME, DL_UPLOADUSERNAME, COUNT(DISTINCT(DLH2.DLH_VERSION)) AS CNT FROM (DOCLIST DL, DOCLISTHISTORY DLH) LEFT JOIN DOCLISTHISTORY DLH2 ON DLH2.DL_ID=DL.DL_ID WHERE DLH.DL_ID=DL.DL_ID AND (DL_UPLOADDATETIME > ( DATE_SUB( NOW( ) , INTERVAL %s DAY ) ) OR DLH.DLH_DATETIME > ( DATE_SUB( NOW( ) , INTERVAL %s DAY ) ) ) GROUP BY DL.DL_ID ORDER BY 4 DESC";

	$qr_dd_selectFreqFilesStatsByDateRange = "SELECT DISTINCT(DL.DL_ID), DL_FILENAME, DL_UPLOADUSERNAME, COUNT(DISTINCT(DLH2.DLH_VERSION)) AS CNT FROM (DOCLIST DL, DOCLISTHISTORY DLH) LEFT JOIN DOCLISTHISTORY DLH2 ON DLH2.DL_ID=DL.DL_ID WHERE DLH.DL_ID=DL.DL_ID AND ( (DL_UPLOADDATETIME >= '%s' AND DL_UPLOADDATETIME <= '%s') OR (DLH.DLH_DATETIME >= '%s' AND DLH.DLH_DATETIME <= '%s') ) GROUP BY DL.DL_ID ORDER BY 4 DESC";

?>