<?php

	//
	// Issue Tracking DBSM-dependent queries
	//
	// Realization for mySQL
	//

	$qr_it_shifttemplatetransitions = "update ISSUETRANSITIONTEMPLATESCHEMA set ITS_NUM=(ITS_NUM+%s) where ITS_NUM <> -1 and ITT_ID='!ITT_ID!'";

	$qr_it_project_active_works = "SELECT PW.P_ID, PW.PW_ID, PW.PW_DESC, PW.PW_ENDDATE FROM PROJECT P, WORKASSIGNMENT WA, PROJECTWORK PW WHERE P.P_ID=WA.P_ID AND WA.P_ID='!P_ID!' AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID %s AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) ORDER BY (PW_STARTDATE IS NULL), PW_STARTDATE, PW_ID";

	$qr_it_all_project_works = "SELECT PW.P_ID, PW.PW_ID, PW.PW_DESC, PW.PW_ENDDATE FROM PROJECTWORK PW WHERE PW.P_ID='!P_ID!' %s ORDER BY (PW_STARTDATE IS NULL), PW_STARTDATE, PW_ID";

	$qr_it_active_issue_assignment = "SELECT COUNT(*) FROM WORKASSIGNMENT WA, PROJECTWORK PW WHERE WA.P_ID='!P_ID!' AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND PW.PW_ID='!PW_ID!'";

	$qr_it_assigned_projects = "SELECT DISTINCT P.P_ID, P.P_DESC, P.P_ENDDATE FROM PROJECT P, WORKASSIGNMENT WA, PROJECTWORK PW WHERE P.P_ID=WA.P_ID AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND (PW.PW_ENDDATE > CURDATE() OR PW.PW_ENDDATE IS NULL) AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) ORDER BY P_DESC";

	$qr_it_assigned_projects_custumers = "SELECT DISTINCT C.C_ID, P.P_ID, C.C_NAME, P.P_DESC, P.P_ENDDATE FROM PROJECT P, CUSTOMER C, WORKASSIGNMENT WA, PROJECTWORK PW WHERE P.P_ID=WA.P_ID AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND (PW.PW_ENDDATE > CURDATE() OR PW.PW_ENDDATE IS NULL) AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) AND C.C_ID=P.C_ID ORDER BY P.P_ID>0, C.C_NAME, P.P_DESC";

	$qr_it_manager_projects = "SELECT DISTINCT C.C_ID, P.P_ID, C.C_NAME, P.P_DESC, P.P_ENDDATE FROM PROJECT P, CUSTOMER C WHERE P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND C.C_ID=P.C_ID AND P.U_ID_MANAGER='!U_ID!' ORDER BY C.C_NAME, P.P_DESC";

	$qr_it_shifttransitions = "UPDATE ISSUETRANSITIONSCHEMA SET ITS_NUM=(ITS_NUM+%s) WHERE ITS_NUM <> -1 AND P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_all_project_issue_attachments = "SELECT PW.PW_ID, I.I_ID, I.I_ATTACHMENT, I.I_NUM, I.I_DESC FROM PROJECTWORK PW, ISSUE I WHERE PW.P_ID='!P_ID!' AND I.P_ID=PW.P_ID AND I.PW_ID=PW.PW_ID AND I.I_ATTACHMENT IS NOT NULL AND I.I_ATTACHMENT <> '' ORDER BY PW.PW_ID";

	$qr_it_all_project_trans_attachments = "SELECT ITL.ITL_ID, I.PW_ID, I.I_NUM, I.I_DESC, ITL.I_ID, ITL.ITL_ATTACHMENT FROM PROJECTWORK PW, ISSUE I, ISSUETRANSITIONLOG ITL WHERE I.I_ID = ITL.I_ID AND PW.P_ID='!P_ID!' AND I.P_ID=PW.P_ID AND I.PW_ID=PW.PW_ID AND ITL.ITL_ATTACHMENT IS NOT NULL AND ITL.ITL_ATTACHMENT <> '' ORDER BY PW.PW_ID";

	$qr_it_active_issue_attachments = "SELECT PW.PW_ID, I.I_ID, I.I_ATTACHMENT, I.I_NUM, I.I_DESC FROM PROJECTWORK PW, WORKASSIGNMENT WA, ISSUE I WHERE WA.P_ID='!P_ID!' AND WA.U_ID='!U_ID!' AND I.PW_ID=WA.PW_ID AND I.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND PW.P_ID=WA.P_ID AND I.I_ATTACHMENT IS NOT NULL AND I.I_ATTACHMENT <> '' ORDER BY PW.PW_ID";

	$qr_it_active_trans_attachments = "SELECT I.I_DESC, I.PW_ID, I.I_NUM, ITL.ITL_ID, I.I_ID, ITL.ITL_ATTACHMENT FROM PROJECTWORK PW, WORKASSIGNMENT WA, ISSUE I, ISSUETRANSITIONLOG ITL WHERE ITL.I_ID=I.I_ID AND WA.P_ID='!P_ID!' AND WA.U_ID='!U_ID!' AND I.PW_ID=WA.PW_ID AND I.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND PW.P_ID=WA.P_ID AND ITL.ITL_ATTACHMENT IS NOT NULL AND ITL.ITL_ATTACHMENT <> '' ORDER BY PW.PW_ID";

	$qr_it_search_issues = "SELECT I.*, ITS.ITS_COLOR,
							C1.C_LASTNAME AS A_LASTNAME, C1.C_FIRSTNAME AS A_FIRSTNAME, C1.C_MIDDLENAME AS A_MIDDLENAME, C1.C_EMAILADDRESS AS A_EMAILADDRESS,
							C2.C_LASTNAME AS S_LASTNAME, C2.C_FIRSTNAME AS S_FIRSTNAME, C2.C_MIDDLENAME AS S_MIDDLENAME, C2.C_EMAILADDRESS AS S_EMAILADDRESS,
							C3.C_LASTNAME AS AU_LASTNAME, C3.C_FIRSTNAME AS AU_FIRSTNAME, C3.C_MIDDLENAME AS AU_MIDDLENAME, C3.C_EMAILADDRESS AS AU_EMAILADDRESS
							FROM ISSUE I
								LEFT JOIN ISSUETRANSITIONSCHEMA ITS ON ITS_STATUS=I.I_STATUSCURRENT AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID
								LEFT JOIN WBS_USER U1 ON U1.U_ID=I.U_ID_ASSIGNED
								LEFT JOIN CONTACT C1 ON C1.C_ID=U1.C_ID
								LEFT JOIN WBS_USER U2 ON U2.U_ID=I.U_ID_SENDER
								LEFT JOIN CONTACT C2 ON C2.C_ID=U2.C_ID
								LEFT JOIN WBS_USER U3 ON U3.U_ID=I.U_ID_AUTHOR
								LEFT JOIN CONTACT C3 ON C3.C_ID=U3.C_ID
							WHERE I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' %s
							ORDER BY I.I_PRIORITY desc, I.I_STARTDATE asc, I.I_NUM";

	$qr_it_search_issuescount = "SELECT COUNT(I.I_ID) FROM ISSUE I, ISSUETRANSITIONSCHEMA ITS WHERE I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' AND ITS_STATUS=I.I_STATUSCURRENT AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID %s";

	$qr_it_search_issuescount_selected = "SELECT COUNT(I.I_ID) FROM ISSUE I, ISSUETRANSITIONSCHEMA ITS WHERE I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' AND ITS_STATUS=I.I_STATUSCURRENT AND ITS.P_ID=I.P_ID AND (I.I_ID in (%s)) AND ITS.PW_ID=I.PW_ID %s";

	$qr_it_all_user_works = "SELECT P.P_ID, PW.PW_ID, PW.PW_DESC, P.P_ID, PW.PW_ENDDATE FROM PROJECT P, WORKASSIGNMENT WA, PROJECTWORK PW WHERE WA.P_ID=P.P_ID AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) %s ORDER BY P.P_ID>0, PW_STARTDATE";

	$qr_it_all_manager_works = "SELECT P.P_ID, PW.PW_ID, PW.PW_DESC, P.P_ID FROM PROJECT P, PROJECTWORK PW WHERE PW.P_ID=P.P_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) AND P.U_ID_MANAGER='!U_ID!' %s ORDER BY PW_STARTDATE";

	$qr_it_opened_manager_projects = "SELECT DISTINCT C.C_ID, P.P_ID, C.C_NAME, P.P_DESC, P.P_ENDDATE FROM PROJECT P, CUSTOMER C WHERE P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) AND C.C_ID=P.C_ID AND P.U_ID_MANAGER='!U_ID!' ORDER BY C.C_NAME, P.P_DESC";

	$qr_it_select_project_works_ordered = "SELECT *, ((PW_ENDDATE IS NOT NULL AND PW_DUEDATE IS NOT NULL AND PW_ENDDATE > PW_DUEDATE) OR (PW_ENDDATE IS NULL AND PW_DUEDATE < CURDATE())) as OVERDUE, (PW_ENDDATE IS NOT NULL AND PW_ENDDATE <= NOW()) AS COMPLETE FROM PROJECTWORK WHERE P_ID='!P_ID!' ORDER BY PW_ID";

	//
	// Issue Statistics Matrix queries
	//

	$qr_it_ism_proj_assigned = "SELECT COUNT(I.I_ID) AS I_COUNT, I.P_ID AS ROW_ID, P.P_DESC AS ROW_NAME, I.U_ID_ASSIGNED AS COL_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME, C.C_NAME,  CA.C_EMAILADDRESS FROM ( ISSUE I, PROJECT P, CUSTOMER C ) LEFT JOIN WBS_USER U ON U.U_ID=I.U_ID_ASSIGNED LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID WHERE P.P_ID=I.P_ID AND C.C_ID=P.C_ID GROUP BY I.P_ID, I.U_ID_ASSIGNED ORDER BY P.P_DESC, I.U_ID_ASSIGNED";

	$qr_it_ism_assigned_status = "SELECT COUNT(I.I_ID) AS I_COUNT, I.U_ID_ASSIGNED AS ROW_ID, I.I_STATUSCURRENT AS COL_ID, I.I_STATUSCURRENT AS COL_NAME, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM ISSUE I LEFT JOIN WBS_USER U ON U.U_ID=I.U_ID_ASSIGNED LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID GROUP BY I.U_ID_ASSIGNED, I.I_STATUSCURRENT ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS, I.I_STATUSCURRENT";

	$qr_it_ism_assigned_priority = "SELECT COUNT(I.I_ID) AS I_COUNT, I.U_ID_ASSIGNED AS ROW_ID, I.I_PRIORITY AS COL_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS  FROM ISSUE I LEFT JOIN WBS_USER U ON U.U_ID=I.U_ID_ASSIGNED LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID GROUP BY I.U_ID_ASSIGNED, I.I_PRIORITY ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS, I.I_PRIORITY";

	$qr_it_ism_work_assigned = "SELECT COUNT(I.I_ID) AS I_COUNT, I.PW_ID AS ROW_ID, PW.PW_DESC AS ROW_NAME, I.U_ID_ASSIGNED AS COL_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS  FROM ( ISSUE I, PROJECTWORK PW ) LEFT JOIN WBS_USER U ON U.U_ID=I.U_ID_ASSIGNED LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID WHERE PW.P_ID=I.P_ID AND PW.PW_ID=I.PW_ID AND I.P_ID='!P_ID!' GROUP BY I.PW_ID, I.U_ID_ASSIGNED ORDER BY I.PW_ID, PW.PW_DESC, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS";

	$qr_it_ism_assigned_status_proj = "SELECT COUNT(I.I_ID) AS I_COUNT, I.U_ID_ASSIGNED AS ROW_ID, I.I_STATUSCURRENT AS COL_ID, I.I_STATUSCURRENT AS COL_NAME, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM ISSUE I LEFT JOIN WBS_USER U ON U.U_ID=I.U_ID_ASSIGNED LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID WHERE I.P_ID='!P_ID!' GROUP BY I.U_ID_ASSIGNED, I.I_STATUSCURRENT ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS, I.I_STATUSCURRENT";

	$qr_it_ism_assigned_priority_proj = "SELECT COUNT(I.I_ID) AS I_COUNT, I.U_ID_ASSIGNED AS ROW_ID, I.I_PRIORITY AS COL_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM ISSUE I LEFT JOIN WBS_USER U ON U.U_ID=I.U_ID_ASSIGNED LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID WHERE I.P_ID='!P_ID!' GROUP BY I.U_ID_ASSIGNED, I.I_PRIORITY ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS, I.I_PRIORITY";

	//
	// Issue filters queries
	//
	$qr_it_assigned_issue_states = "SELECT DISTINCT ITS.ITS_STATUS FROM ISSUETRANSITIONSCHEMA ITS, PROJECT P, WORKASSIGNMENT WA, PROJECTWORK PW WHERE ITS.P_ID=P.P_ID AND ITS.PW_ID=PW.PW_ID AND P.P_ID=WA.P_ID AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) ORDER BY P_DESC";

	$qr_it_manager_projects_workassignments = "SELECT DISTINCT WA.U_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM WORKASSIGNMENT WA, PROJECTWORK PW, PROJECT P, WBS_USER U, CONTACT CA WHERE PW.P_ID=WA.P_ID AND CA.C_ID=U.C_ID AND PW.PW_ID=WA.PW_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND P.P_ID=WA.P_ID AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) AND U.U_ID=WA.U_ID AND P.U_ID_MANAGER='!U_ID!' ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS";

	$qr_it_assigned_workassignments = "SELECT DISTINCT WA1.U_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM WORKASSIGNMENT WA, WORKASSIGNMENT WA1, PROJECTWORK PW, PROJECT P, WBS_USER U, CONTACT CA WHERE WA.U_ID='!U_ID!' AND CA.C_ID=U.C_ID AND WA1.P_ID=WA.P_ID AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID AND (PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL) AND (PW.PW_ENDDATE > CURDATE() OR PW.PW_ENDDATE IS NULL) AND P.P_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND (P.P_ENDDATE > CURDATE() OR P.P_ENDDATE IS NULL) AND P.P_ID=PW.P_ID AND U.U_ID=WA1.U_ID ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS ";

	$qr_it_filterStatesChunk = "ITS.ITS_STATUS NOT IN ('%s')";

	$qr_it_filterAssignedChunk = "I.U_ID_ASSIGNED = '%s'";

	$qr_it_filterNotAssignedChunk = "(I.U_ID_ASSIGNED IS NULL OR I.U_ID_ASSIGNED='')";

	$qr_it_filterSenderChunk = "I.U_ID_SENDER = '%s'";

	$qr_it_filterAuthorChunk = "I.U_ID_AUTHOR = '%s'";

	$qr_it_filterOpenIssuesChunk = "I.I_CLOSEDATE IS NULL";

	$qr_it_filterCompleteIssuesChunk = "I.I_CLOSEDATE IS NOT NULL";

	$qr_it_filterDescChunk = "UPPER(I.I_DESC) like '%%%s%%'";

	$qr_it_filterDateChunk = "((TO_DAYS(NOW()) - TO_DAYS(I.I_STARTDATE) + 1) > '%s')";

	$qr_it_filterLastDaysChunk = "((TO_DAYS(NOW()) - TO_DAYS(I.I_STARTDATE)) < '%s')";

	$qr_it_filterStatusDateChunk = "(((TO_DAYS(NOW()) - TO_DAYS(I.I_STATUSCURRENTDATE) + 1) > '%s') AND I.I_CLOSEDATE IS NULL)";

	$qr_it_filterActiveWorksChunk = " (PW.PW_ENDDATE > CURDATE() OR PW.PW_ENDDATE IS NULL) ";

	$qr_it_filterClosedWorksChunk = " (PW.PW_ENDDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) AND PW.PW_ENDDATE IS NOT NULL) ";

	$qr_it_openedWorksChunk = "(PW.PW_STARTDATE <= DATE_ADD(CURDATE(), INTERVAL 1 DAY) OR PW.PW_STARTDATE IS NULL)";

	//
	// Issue print reports for Statistics Matrix filters
	//

	$qr_it_ism_issuerep_proj_chunk = "AND P_ID='%s'";

	$qr_it_ism_issuerep_status_chunk = "AND I.I_STATUSCURRENT = '!I_STATUSCURRENT!'";

	$qr_it_ism_issuerep_assigned_chunk = "AND %s";

	$qr_it_ism_issuerep_priority_chunk = "AND I.I_PRIORITY = '!I_PRIORITY!'";

	$qr_it_ism_issuerep_assigned_status_chunk = "AND %s AND I.I_STATUSCURRENT = '!I_STATUSCURRENT!'";

	$qr_it_ism_issuerep_assigned_priority_chunk = "AND %s AND I.I_PRIORITY = '!I_PRIORITY!'";

	$qr_it_ism_issuerep_work_chunk = "AND PW_ID='%s'";

	//
	// Issue dynamic report queries
	//

	$qr_it_idr_project_chunk = "I.P_ID='%s'";

	$qr_it_idr_work_chunk = "I.PW_ID='%s'";

	$qr_it_idr_status_chunk = "I.I_STATUSCURRENT IN (%s)";

	$qr_it_idr_user_reminder_chunk = "I.I_ID IN (%s) AND I.U_ID_ASSIGNED='%s'";

	$qr_it_count_user_issues = "SELECT COUNT(*) AS ISSUECOUNT, I.U_ID_ASSIGNED, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM ISSUE I, WBS_USER U, CONTACT CA WHERE CA.C_ID=U.C_ID AND U.U_ID=I.U_ID_ASSIGNED AND I.I_ID IN (%s) GROUP BY I.U_ID_ASSIGNED ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS";

	$qr_it_idr_selectdata = "SELECT
                PW.PW_DESC, I.I_ID, I.I_PRIORITY, ITS.ITS_COLOR, P.P_DESC, I.I_DESC,
                I.I_STATUSCURRENT, I.I_STATUSCURRENTDATE, I.I_STARTDATE, I.U_ID_ASSIGNED,
                CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME, C.C_NAME,  CA.C_EMAILADDRESS, I.PW_ID,
                I.I_NUM
              FROM ( ISSUE I, PROJECT P, CUSTOMER C, PROJECTWORK PW )
                LEFT JOIN WBS_USER U ON U.U_ID=I.U_ID_ASSIGNED
                LEFT JOIN CONTACT CA ON CA.C_ID=U.C_ID
                LEFT JOIN ISSUETRANSITIONSCHEMA ITS ON ITS_STATUS=I.I_STATUSCURRENT AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID
              WHERE
                P.P_ID=I.P_ID AND C.C_ID=P.C_ID AND PW.P_ID=I.P_ID
                AND PW.PW_ID=I.PW_ID
				%s
              ORDER BY %s";
?>