<?php

	//
	// Issue Tracking DBSM-independent queries
	//

	//
	// Transition schemas
	//
	$qr_it_selecttemplateschematransitions = "SELECT ITS_NUM, ITTS_STATUS FROM ISSUETRANSITIONTEMPLATESCHEMA WHERE ITT_ID='!ITT_ID!' ORDER BY ITS_NUM";

	$qr_it_select_transition = "SELECT * FROM ISSUETRANSITIONTEMPLATESCHEMA WHERE ITT_ID='!ITT_ID!' AND ITS_NUM='!ITS_NUM!'";

	$qr_it_add_comment = "INSERT INTO `ISSUETRANSITIONLOG` (`I_ID`, `ITL_ID`, `ITL_STATUS`, `ITL_DESC`, `ITL_OLDCONTENT`, `U_ID_SENDER`, `ITL_DATETIME`) VALUES ('!I_ID!', '!ITL_ID!', '!ITL_STATUS!', '!ITL_DESC!', '!ITL_OLDCONTENT!', '!U_ID_SENDER!', NOW())";

	$qr_it_get_last_comment = "SELECT * FROM ISSUETRANSITIONLOG WHERE ITL_ID = '!ITL_ID!' AND I_ID = '!I_ID!' LIMIT 1";

	$qr_it_get_max_itl = "SELECT MAX(ITL_ID) as MAX FROM `ISSUETRANSITIONLOG` WHERE I_ID = '!I_ID!'";

	$qr_it_delete_template = "DELETE FROM ISSUETRANSITIONTEMPLATE WHERE ITT_ID='!ITT_ID!'";

	$qr_it_delete_templatestatues = "DELETE FROM ISSUETRANSITIONTEMPLATESCHEMA WHERE ITT_ID='!ITT_ID!'";

	$qr_it_select_template = "SELECT * FROM ISSUETRANSITIONTEMPLATE WHERE ITT_ID='!ITT_ID!'";

	$qr_it_templatelist = "SELECT * FROM ISSUETRANSITIONTEMPLATE ORDER BY ITT_NAME";

	$qr_it_createtemplate = "INSERT INTO ISSUETRANSITIONTEMPLATE(ITT_ID, ITT_NAME, ITT_STATUS) VALUES('!ITT_ID!', '!ITT_NAME!', '!ITT_STATUS!')";

	$qr_it_getmaxITT_ID = "SELECT MAX(ITT_ID) FROM ISSUETRANSITIONTEMPLATE";

	$qr_it_inserttemplatestate = "INSERT INTO ISSUETRANSITIONTEMPLATESCHEMA(ITT_ID, ITS_NUM, ITTS_STATUS, ITTS_ALLOW_EDIT, ITTS_ALLOW_DELETE, ITTS_ASSIGNMENTOPTION, ITTS_ASSIGNED, ITTS_COLOR, ITTS_ALLOW_DEST, ITTS_DEFAULT_DEST) VALUES ('!ITT_ID!', '!ITS_NUM!', '!ITTS_STATUS!', '!ITTS_ALLOW_EDIT!', '!ITTS_ALLOW_DELETE!', '!ITTS_ASSIGNMENTOPTION!', '!ITTS_ASSIGNED!', '!ITTS_COLOR!', '!ITTS_ALLOW_DEST!', '!ITTS_DEFAULT_DEST!')";

	$qr_it_select_transition_bystatusname = "SELECT * FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_STATUS='!ITS_STATUS!'";

	$qr_ir_select_work_transitions = "SELECT * FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' ORDER BY ITS_NUM";

	$qr_it_select_transition_byitsnum = "SELECT * FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM='!ITS_NUM!'";

	$qr_it_select_first_transition_num = "SELECT MIN(ITS_NUM) FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_select_project_manager_name = "SELECT P.U_ID_MANAGER, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM PROJECT P LEFT JOIN WBS_USER U ON U.U_ID = P.U_ID_MANAGER LEFT JOIN CONTACT CA ON CA.C_ID = U.C_ID WHERE P_ID='!P_ID!'";

	$qr_it_templateexists = "SELECT COUNT(*) FROM ISSUETRANSITIONTEMPLATE WHERE ITT_ID='!ITT_ID!'";

	$qr_it_workissuestates = "SELECT DISTINCT I_STATUSCURRENT FROM ISSUE WHERE PW_ID='!PW_ID!' AND P_ID='!P_ID!'";

	$qr_it_templatenameexists = "SELECT COUNT(*) FROM ISSUETRANSITIONTEMPLATE WHERE UPPER(ITT_NAME)=UPPER('!ITT_NAME!')";

	$qr_it_issue_real_transitions = "SELECT I.*, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM ISSUETRANSITIONSCHEMA I LEFT JOIN WBS_USER U ON U.U_ID = I.U_ID_ASSIGNED LEFT JOIN CONTACT CA ON CA.C_ID = U.C_ID WHERE I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' ORDER BY I.ITS_NUM";

	$qr_it_issue_closed_transition = "SELECT * FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM = '!ITS_NUM!' ORDER BY ITS_NUM";

	$qr_it_schematransitionscount = "SELECT COUNT(*) FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_insertsimpletransition = "INSERT INTO ISSUETRANSITIONSCHEMA(ITS_NUM, P_ID, PW_ID, ITS_COLOR, ITS_STATUS) VALUES ('!ITS_NUM!', '!P_ID!', '!PW_ID!', '!ITS_COLOR!', '!ITS_STATUS!')";

	$qr_it_selectissueworktransition = "SELECT * FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM='!ITS_NUM!'";

	$qr_it_selectnextissueworktransitionnum = "SELECT ITS_NUM FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM>'!ITS_NUM!'";

	$qr_it_deletetransition = "DELETE FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM='!ITS_NUM!'";

	$qr_it_selectissueworktransitionnums = "SELECT ITS_NUM FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' ORDER BY ITS_NUM";

	$qr_it_updateissueworktransitionnum = "UPDATE ISSUETRANSITIONSCHEMA SET ITS_NUM='!NEW_NUM!' WHERE ITS_NUM='!ITS_NUM!' AND PW_ID='!PW_ID!' AND P_ID='!P_ID!'";

	$qr_it_inserttransition_full = "INSERT INTO ISSUETRANSITIONSCHEMA(P_ID, PW_ID, ITS_NUM, ITS_STATUS, ITS_ALLOW_EDIT, ITS_ALLOW_DELETE, ITS_ASSIGNMENTOPTION, ITS_COLOR, U_ID_ASSIGNED, ITS_ALLOW_DEST, ITS_DEFAULT_DEST) VALUES ('!P_ID!', '!PW_ID!', '!ITS_NUM!', '!ITS_STATUS!', '!ITS_ALLOW_EDIT!', '!ITS_ALLOW_DELETE!', '!ITS_ASSIGNMENTOPTION!', '!ITS_COLOR!', '!U_ID_ASSIGNED!', '!ITS_ALLOW_DEST!', '!ITS_DEFAULT_DEST!')";

	$qr_it_updatetransition = "UPDATE ISSUETRANSITIONSCHEMA SET ITS_STATUS='!ITS_STATUS!', ITS_ALLOW_EDIT='!ITS_ALLOW_EDIT!', ITS_ALLOW_DELETE='!ITS_ALLOW_DELETE!', ITS_ASSIGNMENTOPTION='!ITS_ASSIGNMENTOPTION!', ITS_COLOR='!ITS_COLOR!', U_ID_ASSIGNED='!U_ID_ASSIGNED!', ITS_ALLOW_DEST='!ITS_ALLOW_DEST!', ITS_DEFAULT_DEST='!ITS_DEFAULT_DEST!' WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM='!ITS_NUM!'";

	$qr_it_updatetransitionalloweddest = "UPDATE ISSUETRANSITIONSCHEMA SET ITS_ALLOW_DEST='!ITS_ALLOW_DEST!' WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM='!ITS_NUM!'";

	$qr_it_updatetransitiondefaultddest = "UPDATE ISSUETRANSITIONSCHEMA SET ITS_DEFAULT_DEST='!ITS_DEFAULT_DEST!' WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_DEFAULT_DEST='!PREV_NAME!'";

	$qr_it_updatetranscolor = "UPDATE ISSUETRANSITIONSCHEMA SET ITS_COLOR='!ITS_COLOR!' WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM='!ITS_NUM!'";

	$qr_it_selectschematransitions = "SELECT ITS_NUM, ITS_STATUS FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' ORDER BY ITS_NUM";

	$qr_it_selectschematransitionsexcl = "SELECT ITS_NUM, ITS_STATUS FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM<>'!ITS_NUM!' ORDER BY ITS_NUM";

	$qr_it_maxtransitionnum = "SELECT MAX(ITS_NUM) AS NEXT_NUM FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_issuestatuscount = "SELECT COUNT(I.I_ID) FROM ISSUE I, ISSUETRANSITIONSCHEMA ITS WHERE I.I_STATUSCURRENT=ITS.ITS_STATUS AND I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID AND ITS.ITS_NUM='!ITS_NUM!'";

	$qr_it_schematransisionsused = "SELECT COUNT(I.I_ID) FROM ISSUE I, ISSUETRANSITIONSCHEMA ITS WHERE I.I_STATUSCURRENT=ITS.ITS_STATUS AND I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID";

	$qr_it_deleteschematransitions = "DELETE FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_selecttemplateschematransitions_full = "SELECT * FROM ISSUETRANSITIONTEMPLATESCHEMA WHERE ITT_ID='!ITT_ID!' ORDER BY ITS_NUM";

	$qr_it_select_issue_states = "SELECT DISTINCT ITS_STATUS FROM ISSUETRANSITIONSCHEMA ORDER BY ITS_STATUS";

	$qr_it_selectTransitionShemaCountByStatus = "SELECT COUNT(*) FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_STATUS='!ITS_STATUS!'";

	$qr_it_selectIssuesByStatus = "SELECT * FROM ISSUE WHERE I_STATUSCURRENT='!I_STATUSCURRENT!' AND P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_updateStatus = "UPDATE ISSUE SET I_STATUSCURRENT='!I_STATUSCURRENT!' WHERE I_ID='!I_ID!'";

	$qr_it_updateCloseDate = "UPDATE ISSUE SET I_CLOSEDATE='!I_CLOSEDATE!' WHERE I_ID='!I_ID!'";

	$qr_it_updateIssueStatusName = "UPDATE ISSUE SET I_STATUSCURRENT='!I_STATUSCURRENT!' WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND I_STATUSCURRENT='!PREVSTATUSNAME!'";

	$qr_it_resetTemplateDefault = "UPDATE ISSUETRANSITIONTEMPLATE SET ITT_DEFAULT=0";

	$qr_it_setTemplateDefault = "UPDATE ISSUETRANSITIONTEMPLATE SET ITT_DEFAULT='!ITT_DEFAULT!' WHERE ITT_ID='!ITT_ID!'";

	$qr_it_selectDefaultTemplate = "SELECT ITT_ID FROM ISSUETRANSITIONTEMPLATE WHERE ITT_DEFAULT=1";

	$qr_it_initWorkflow = "INSERT INTO ISSUETRANSITIONSCHEMA (P_ID,PW_ID,ITS_NUM,ITS_STATUS,ITS_ALLOW_EDIT,ITS_ALLOW_DELETE,ITS_ASSIGNMENTOPTION,U_ID_ASSIGNED,ITS_COLOR,ITS_ALLOW_DEST) values ('!P_ID!', '!PW_ID!', 1, 'Start', null, null, null, null, null, 'Complete'), ('!P_ID!', '!PW_ID!', 2, 'Complete', 0, 0, -1, null, 0, null)";

	//
	// Add/mod issue pages
	//
	$qr_it_select_issue_assignments = "SELECT WA.U_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM WORKASSIGNMENT WA, WBS_USER UL, CONTACT CA WHERE CA.C_ID=UL.C_ID AND UL.U_ID=WA.U_ID AND WA.P_ID='!P_ID!' AND WA.PW_ID='!PW_ID!' ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS";

	$qr_it_insertworkassignment = "INSERT INTO WORKASSIGNMENT(P_ID, PW_ID, U_ID) VALUES ('!P_ID!', '!PW_ID!', '!U_ID!')";

	$qr_it_addissue = "INSERT INTO ISSUE(I_ID, P_ID, PW_ID, I_NUM, U_ID_ASSIGNED, I_PRIORITY, I_STARTDATE, I_DESC, I_ATTACHMENT, U_ID_AUTHOR) VALUES ('!I_ID!', '!P_ID!', '!PW_ID!', '!I_NUM!', '!U_ID_ASSIGNED!', '!I_PRIORITY!', '!I_STARTDATE!', '!I_DESC!', '!I_ATTACHMENT!', '!U_ID_AUTHOR!')";

	$qr_it_add_issue_full = "INSERT INTO ISSUE(I_ID, P_ID, PW_ID, I_NUM, I_STATUSCURRENT, U_ID_ASSIGNED, U_ID_SENDER, I_STATUSCURRENTDATE, I_PRIORITY, I_STARTDATE, I_DUEDATE, I_DESC, I_ATTACHMENT, I_CLOSEDATE, U_ID_AUTHOR, I_TRANSITION_DESC)
								VALUES ('!I_ID!', '!P_ID!', '!PW_ID!', '!I_NUM!', '!I_STATUSCURRENT!', '!U_ID_ASSIGNED!', '!U_ID_SENDER!', '!I_STATUSCURRENTDATE!', '!I_PRIORITY!', '!I_STARTDATE!', '!I_DUEDATE!', '!I_DESC!', '!I_ATTACHMENT!', '!I_CLOSEDATE!', '!U_ID_AUTHOR!', '!I_TRANSITION_DESC!')";

	$qr_it_moveissue = "UPDATE ISSUE SET P_ID='!P_ID!', PW_ID='!PW_ID!', I_NUM='!I_NUM!', I_STATUSCURRENT='!I_STATUSCURRENT!' WHERE I_ID='!I_ID!'";

	$qr_it_maxissueid = "SELECT MAX(I_ID) AS MAXID FROM ISSUE";

	$qr_it_maxissuenum = "SELECT MAX(I_NUM) AS MAXNUM FROM ISSUE WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_updateissue = "UPDATE ISSUE SET U_ID_ASSIGNED='!U_ID_ASSIGNED!', I_PRIORITY='!I_PRIORITY!', I_DESC='!I_DESC!', I_ATTACHMENT='!I_ATTACHMENT!' WHERE I_ID='!I_ID!'";

	$qr_it_select_issues = "SELECT I.*, ITS.ITS_COLOR, C1.C_LASTNAME AS A_LASTNAME, C1.C_FIRSTNAME AS A_FIRSTNAME, C1.C_MIDDLENAME AS A_MIDDLENAME, C1.C_EMAILADDRESS AS A_EMAILADDRESS, C2.C_LASTNAME AS S_LASTNAME, C2.C_FIRSTNAME AS S_FIRSTNAME, C2.C_MIDDLENAME AS S_MIDDLENAME, C2.C_EMAILADDRESS AS S_EMAILADDRESS FROM ISSUE I
							LEFT JOIN ISSUETRANSITIONSCHEMA ITS ON ITS_STATUS=I.I_STATUSCURRENT AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID LEFT JOIN WBS_USER U1 ON U1.U_ID=I.U_ID_ASSIGNED LEFT JOIN CONTACT C1 ON C1.C_ID=U1.C_ID LEFT JOIN WBS_USER U2 ON U2.U_ID=I.U_ID_SENDER LEFT JOIN CONTACT C2 ON C2.C_ID=U2.C_ID
							WHERE I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' ORDER BY I.I_PRIORITY desc, I.I_STARTDATE asc, I.I_ID";

	$qr_it_select_issuescount = "SELECT COUNT(I.I_ID) FROM ISSUE I WHERE I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!'";

	$qr_it_select_issue = "SELECT * FROM ISSUE WHERE I_ID='!I_ID!'";

	$qr_it_select_issuestatusinfo = "SELECT I.*, ITS.ITS_COLOR FROM ISSUE I LEFT JOIN ISSUETRANSITIONSCHEMA ITS ON ITS_STATUS=I.I_STATUSCURRENT AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID WHERE I_ID='!I_ID!'";

	$qr_it_maxitlid = "SELECT MAX(ITL_ID) AS MAXID FROM ISSUETRANSITIONLOG WHERE I_ID='!I_ID!'";

	$qr_it_updateissuestatus = "UPDATE ISSUE SET I_STATUSCURRENT='!I_STATUSCURRENT!', U_ID_ASSIGNED='!U_ID_ASSIGNED!', U_ID_SENDER='!U_ID_SENDER!', I_STATUSCURRENTDATE='!I_STATUSCURRENTDATE!' WHERE I_ID='!I_ID!'";

	$qr_it_insertitl = "INSERT INTO ISSUETRANSITIONLOG(I_ID, ITL_ID, ITL_STATUS, ITL_DESC, ITL_ATTACHMENT, U_ID_ASSIGNED, U_ID_SENDER, ITL_DATETIME, ITL_ISRETURN) VALUES('!I_ID!', '!ITL_ID!', '!ITL_STATUS!', '!ITL_DESC!', '!ITL_ATTACHMENT!', '!U_ID_ASSIGNED!', '!U_ID_SENDER!', '!ITL_DATETIME!', '!ITL_ISRETURN!')";

	$qr_it_previtsstatus = "SELECT * FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM < '!ITS_NUM!' ORDER BY ITS_NUM DESC";

	$qr_it_nextitsstatus = "SELECT * FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND ITS_NUM > '!ITS_NUM!' ORDER BY ITS_NUM";

	$qr_it_issuetranslog = "SELECT ITL.*, C1.C_FIRSTNAME as A_FIRSTNAME, C1.C_LASTNAME as A_LASTNAME, C1.C_MIDDLENAME as A_MIDDLENAME, C1.C_EMAILADDRESS AS A_EMAILADDRESS, C2.C_FIRSTNAME as S_FIRSTNAME, C2.C_LASTNAME as S_LASTNAME, C2.C_MIDDLENAME as S_MIDDLENAME, C2.C_EMAILADDRESS AS S_EMAILADDRESS, ITS.ITS_COLOR FROM ( ISSUETRANSITIONLOG ITL, WBS_USER U2, CONTACT C2, ISSUE I ) LEFT JOIN WBS_USER U1 ON U1.U_ID=ITL.U_ID_ASSIGNED LEFT JOIN CONTACT C1 ON C1.C_ID=U1.C_ID LEFT JOIN ISSUETRANSITIONSCHEMA ITS ON ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID AND ITS.ITS_STATUS=ITL.ITL_STATUS WHERE C2.C_ID=U2.C_ID AND ITL.I_ID='!I_ID!' AND U2.U_ID=ITL.U_ID_SENDER AND I.I_ID=ITL.I_ID ORDER BY ITL_ID";

	$qr_it_deleteissuetranslog = "DELETE FROM ISSUETRANSITIONLOG WHERE I_ID='!I_ID!'";

	$qr_it_selectITLRecord = "SELECT * FROM ISSUETRANSITIONLOG WHERE I_ID='!I_ID!' AND ITL_ID='!ITL_ID!'";

	$qr_it_deleteissue = "DELETE FROM ISSUE WHERE I_ID='!I_ID!'";

	$qr_it_issuetranslogtransition = "SELECT ITL.*, C1.C_FIRSTNAME as A_FIRSTNAME, C1.C_LASTNAME as A_LASTNAME, C1.C_MIDDLENAME as A_MIDDLENAME, C1.C_EMAILADDRESS AS A_EMAILADDRESS, C2.C_FIRSTNAME as S_FIRSTNAME, C2.C_LASTNAME as S_LASTNAME, C2.C_MIDDLENAME as S_MIDDLENAME, C2.C_EMAILADDRESS AS S_EMAILADDRESS, ITS.ITS_COLOR, I.P_ID, I.PW_ID FROM ( ISSUETRANSITIONLOG ITL, WBS_USER U2, CONTACT C2, ISSUE I ) LEFT JOIN WBS_USER U1 ON U1.U_ID=ITL.U_ID_ASSIGNED LEFT JOIN CONTACT C1 ON C1.C_ID=U1.C_ID LEFT JOIN ISSUETRANSITIONSCHEMA ITS ON ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID AND ITS.ITS_STATUS=ITL.ITL_STATUS WHERE C2.C_ID=U2.C_ID AND ITL.I_ID='!I_ID!' AND ITL.ITL_ID='!ITL_ID!' AND U2.U_ID=ITL.U_ID_SENDER AND I.I_ID=ITL.I_ID ORDER BY ITL_ID DESC";

	$qr_it_insertissuemodificationlog = "INSERT INTO ISSUETRANSITIONLOG(I_ID, ITL_ID, ITL_STATUS, U_ID_ASSIGNED, U_ID_SENDER, ITL_DATETIME, ITL_OLDCONTENT) VALUES('!I_ID!', '!ITL_ID!', '!ITL_STATUS!', '!U_ID_ASSIGNED!', '!U_ID_SENDER!', '!ITL_DATETIME!', '!ITL_OLDCONTENT!')";

	$qr_it_user_issue_assignment = "SELECT COUNT(*) FROM ISSUE WHERE (U_ID_ASSIGNED='!U_ID!' OR U_ID_SENDER='!U_ID!') AND I_ID='!I_ID!'";

	$qr_it_selecttransitionlog = "SELECT * FROM ISSUETRANSITIONLOG WHERE I_ID='!I_ID!'";

	$qr_it_updateIssueComment = "UPDATE ISSUE SET I_TRANSITION_DESC='!ITL_DESC!' WHERE I_ID='!I_ID!'";

	$qr_it_selectWorkIssueTransitions = "SELECT ITL.*, I.I_NUM, ITS.ITS_COLOR, C1.C_FIRSTNAME as A_FIRSTNAME, C1.C_LASTNAME as A_LASTNAME, C1.C_MIDDLENAME as A_MIDDLENAME, C1.C_EMAILADDRESS AS A_EMAILADDRESS, C2.C_FIRSTNAME as S_FIRSTNAME, C2.C_LASTNAME as S_LASTNAME, C2.C_MIDDLENAME as S_MIDDLENAME, C2.C_EMAILADDRESS AS S_EMAILADDRESS FROM ( ISSUETRANSITIONLOG ITL, ISSUE I, ISSUETRANSITIONSCHEMA ITS ) LEFT JOIN WBS_USER U1 ON U1.U_ID=ITL.U_ID_ASSIGNED LEFT JOIN CONTACT C1 ON C1.C_ID=U1.C_ID LEFT JOIN WBS_USER U2 ON U2.U_ID=ITL.U_ID_SENDER LEFT JOIN CONTACT C2 ON C2.C_ID=U2.C_ID WHERE ITL.I_ID = I.I_ID AND I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID AND ITS.ITS_STATUS=ITL.ITL_STATUS ORDER BY ITL_DATETIME";
	
	$qr_it_selectWorkIssuesGBP = "SELECT I.*, ITS.ITS_COLOR,
							C1.C_LASTNAME AS A_LASTNAME, C1.C_FIRSTNAME AS A_FIRSTNAME, C1.C_MIDDLENAME AS A_MIDDLENAME, C1.C_EMAILADDRESS AS A_EMAILADDRESS,
							C2.C_LASTNAME AS S_LASTNAME, C2.C_FIRSTNAME AS S_FIRSTNAME, C2.C_MIDDLENAME AS S_MIDDLENAME, C2.C_EMAILADDRESS AS S_EMAILADDRESS,
							C3.C_LASTNAME AS AU_LASTNAME, C3.C_FIRSTNAME AS AU_FIRSTNAME, C3.C_MIDDLENAME AS AU_MIDDLENAME, C3.C_EMAILADDRESS AS AU_EMAILADDRESS
							FROM ISSUE I
								LEFT JOIN ISSUETRANSITIONSCHEMA ITS ON ITS_STATUS=I.I_STATUSCURRENT AND ITS.P_ID=I.P_ID AND ITS.PW_ID=I.PW_ID
								LEFT JOIN WBS_USER U1 ON U1.U_ID=I.U_ID_ASSIGNED
								LEFT JOIN CONTACT C1 ON C1.C_ID=U1.C_ID
								LEFT JOIN WBS_USER U2 ON U2.U_ID=I.U_ID_SENDER
								LEFT JOIN CONTACT C2 ON C2.C_ID=U2.C_ID
								LEFT JOIN WBS_USER U3 ON U3.U_ID=I.U_ID_AUTHOR
								LEFT JOIN CONTACT C3 ON C3.C_ID=U3.C_ID
							ORDER BY I.I_PRIORITY desc, I.I_STARTDATE asc, I.I_NUM";
	
	// Project and works queries
	//
	$qr_it_selectprojectname = "SELECT P.P_DESC, C.C_NAME FROM PROJECT P, CUSTOMER C WHERE P.P_ID='!P_ID!' AND C.C_ID=P.C_ID";

	$qr_it_selectprojectworksdesc = "SELECT PW_DESC FROM PROJECTWORK WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_workexists = "SELECT COUNT(PW_ID) FROM PROJECTWORK WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_allassignedprojects = "SELECT DISTINCT P.P_ID, P.P_DESC, P.P_ENDDATE FROM PROJECT P, WORKASSIGNMENT WA, PROJECTWORK PW WHERE (P.P_ID=WA.P_ID AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID OR P.P_ID=0) ORDER BY P_DESC";

	$qr_it_allassignedprojects_custumers = "SELECT DISTINCT C.C_ID, P.P_ID, C.C_NAME, P.P_DESC, P.P_ENDDATE FROM PROJECT P, CUSTOMER C, WORKASSIGNMENT WA, PROJECTWORK PW WHERE ((P.P_ID=WA.P_ID AND WA.U_ID='!U_ID!' AND PW.P_ID=WA.P_ID AND PW.PW_ID=WA.PW_ID) OR P.P_ID=0)  AND C.C_ID=P.C_ID ORDER BY C.C_NAME, P.P_DESC";

	$qr_it_select_all_projects = "SELECT DISTINCT P.P_ID, P.P_DESC, P.P_ENDDATE FROM PROJECT P ORDER BY P_DESC";

	$qr_it_select_all_projects_customers = "SELECT DISTINCT P.P_ID, P.P_DESC, P.P_ENDDATE, C.C_ID, C.C_NAME FROM PROJECT P, CUSTOMER C WHERE C.C_ID=P.C_ID ORDER BY C.C_NAME, P.P_DESC";

	$qr_it_select_all_projects_customers_activefirst = "SELECT DISTINCT P.P_ID, P.P_DESC, P.P_ENDDATE, (P_ENDDATE IS NOT NULL and P_ENDDATE <= CURDATE()) AS COMPLETE, C.C_ID, C.C_NAME FROM PROJECT P, CUSTOMER C WHERE C.C_ID=P.C_ID ORDER BY (P_ENDDATE <> '' and P_ENDDATE <= CURDATE()), C.C_NAME, P.P_DESC";

	$qr_it_select_works = "SELECT PW_ID, PW_DESC FROM PROJECTWORK WHERE P_ID='!P_ID!' ORDER BY PW_ID";

	$qr_it_selectwork = "SELECT * FROM PROJECTWORK WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_selectworkassignments = "SELECT U_ID FROM WORKASSIGNMENT WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_openissuesexists = "SELECT COUNT(*) FROM ISSUE WHERE I_CLOSEDATE IS NULL AND P_ID='!P_ID!'";

	$qr_it_opentaslissuesexists = "SELECT COUNT(*) FROM ISSUE WHERE I_CLOSEDATE IS NULL AND P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_selectopenissues = "SELECT * FROM ISSUE WHERE I_CLOSEDATE IS NULL AND P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_selectprojects = "SELECT * FROM PROJECT";

	// Issue assignments
	//

	$qr_it_selectworkassignments = "SELECT WA.U_ID, CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS FROM WORKASSIGNMENT WA, WBS_USER U, CONTACT CA WHERE WA.P_ID='!P_ID!' AND CA.C_ID=U.C_ID AND WA.PW_ID='!PW_ID!' AND U.U_ID = WA.U_ID ORDER BY CA.C_LASTNAME, CA.C_FIRSTNAME, CA.C_MIDDLENAME,  CA.C_EMAILADDRESS";

	//
	// Issue filters queries
	//

	$qr_it_select_manager_issuestates = "SELECT DISTINCT ITS.ITS_STATUS FROM ISSUETRANSITIONSCHEMA ITS, PROJECT P WHERE ITS.P_ID=P.P_ID AND P.U_ID_MANAGER='!U_ID!'";

	$qr_it_select_max_filterID = "SELECT MAX(ISSF_ID) FROM ISSUEFILTER WHERE U_ID='!U_ID!'";

	$qr_it_insert_filter = "INSERT INTO ISSUEFILTER(U_ID, ISSF_ID, ISSF_NAME, P_ID, ISSF_HIDDENSTATES, ISFF_U_ID_ASSIGNED, ISFF_U_ID_SENDER, ISFF_DAYSOLD, ISSF_SEARCHSTRING, ISSF_MODIFYDATETIME, ISSF_DAYSAGO, ISSF_PENDING, ISFF_U_ID_AUTHOR, ISSF_ISSUE_COMPLETE, ISSF_WORKSTATE_CREATEDAY_OPT, ISSF_LASTDAYS) VALUES ('!U_ID!', '!ISSF_ID!', '!ISSF_NAME!', '!P_ID!', '!ISSF_HIDDENSTATES!', '!ISFF_U_ID_ASSIGNED!', '!ISFF_U_ID_SENDER!', '!ISFF_DAYSOLD!', '!ISSF_SEARCHSTRING!', '!ISSF_MODIFYDATETIME!', '!ISSF_DAYSAGO!', '!ISSF_PENDING!', '!ISFF_U_ID_AUTHOR!', '!ISSF_ISSUE_COMPLETE!', '!ISSF_WORKSTATE_CREATEDAY_OPT!', '!ISSF_LASTDAYS!')";

	$qr_it_delete_filter = "DELETE FROM ISSUEFILTER WHERE U_ID='!U_ID!' AND ISSF_ID='!ISSF_ID!'";

	$qr_it_select_filter = "SELECT * FROM ISSUEFILTER WHERE U_ID='!U_ID!' AND ISSF_ID='!ISSF_ID!'";

	$qr_it_update_filter = "UPDATE ISSUEFILTER SET ISSF_NAME='!ISSF_NAME!', ISSF_WORKSTATE='!ISSF_WORKSTATE!', ISSF_HIDDENSTATES='!ISSF_HIDDENSTATES!', ISFF_U_ID_ASSIGNED='!ISFF_U_ID_ASSIGNED!', ISFF_U_ID_SENDER='!ISFF_U_ID_SENDER!', ISFF_DAYSOLD='!ISFF_DAYSOLD!', ISSF_SEARCHSTRING='!ISSF_SEARCHSTRING!', ISSF_MODIFYDATETIME='!ISSF_MODIFYDATETIME!', ISSF_DAYSAGO='!ISSF_DAYSAGO!', ISSF_PENDING='!ISSF_PENDING!', ISFF_U_ID_AUTHOR='!ISFF_U_ID_AUTHOR!', ISSF_ISSUE_COMPLETE='!ISSF_ISSUE_COMPLETE!', ISSF_WORKSTATE_CREATEDAY_OPT='!ISSF_WORKSTATE_CREATEDAY_OPT!', ISSF_LASTDAYS='!ISSF_LASTDAYS!' WHERE U_ID='!U_ID!' AND ISSF_ID='!ISSF_ID!'";

	$qr_it_select_filters = "SELECT * FROM ISSUEFILTER WHERE U_ID='!U_ID!' ORDER BY ISSF_ID";

	//
	// Issue Statistics Matrix queries
	//

	$qr_it_ism_proj_status = "SELECT COUNT(I.I_ID) AS I_COUNT, I.P_ID AS ROW_ID, P.P_DESC AS ROW_NAME, I.I_STATUSCURRENT AS COL_ID, I.I_STATUSCURRENT AS COL_NAME, C.C_NAME FROM ISSUE I, PROJECT P, CUSTOMER C WHERE P.P_ID=I.P_ID AND C.C_ID=P.C_ID GROUP BY I.P_ID, I.I_STATUSCURRENT  ORDER BY P.P_DESC, I.I_STATUSCURRENT";

	$qr_it_ism_proj_priority = "SELECT COUNT(I.I_ID) AS I_COUNT, I.P_ID AS ROW_ID, P.P_DESC AS ROW_NAME, I.I_PRIORITY AS COL_ID, C.C_NAME FROM ISSUE I, PROJECT P, CUSTOMER C WHERE P.P_ID=I.P_ID AND C.C_ID=P.C_ID GROUP BY I.P_ID, I.I_PRIORITY  ORDER BY P.P_DESC, I.I_PRIORITY";

	$qr_it_ism_work_status = "SELECT COUNT(I.I_ID) AS I_COUNT, I.PW_ID AS ROW_ID, PW.PW_DESC AS ROW_NAME, I.I_STATUSCURRENT AS COL_ID, I.I_STATUSCURRENT AS COL_NAME FROM ISSUE I, PROJECTWORK PW WHERE PW.P_ID=I.P_ID AND PW.PW_ID=I.PW_ID AND I.P_ID='!P_ID!' GROUP BY I.PW_ID, I.I_STATUSCURRENT ORDER BY I.PW_ID, PW.PW_DESC, I.I_STATUSCURRENT";

	$qr_it_ism_work_priority = "SELECT COUNT(I.I_ID) AS I_COUNT, I.PW_ID AS ROW_ID, PW.PW_DESC AS ROW_NAME, I.I_PRIORITY AS COL_ID FROM ISSUE I, PROJECTWORK PW WHERE PW.P_ID=I.P_ID AND PW.PW_ID=I.PW_ID AND I.P_ID='!P_ID!' GROUP BY I.PW_ID, I.I_PRIORITY ORDER BY I.PW_ID, PW.PW_DESC, I.I_PRIORITY";

	//
	// Issue print reports for Statistics Matrix
	//

	$qr_it_ism_issuerep_works = "SELECT PW_ID, PW_DESC FROM PROJECTWORK WHERE P_ID='!P_ID!' %s ORDER BY PW_ID";

	$qr_it_ism_issuerep_projects = "SELECT DISTINCT P.P_ID, P.P_DESC, P.P_ENDDATE, C.C_ID, C.C_NAME FROM PROJECT P, CUSTOMER C WHERE C.C_ID=P.C_ID %s ORDER BY C.C_NAME, P.P_DESC";

	//
	// Issue dynamic report queries
	//

	$qr_it_idr_select_issuedata = "SELECT P.P_DESC, I.* FROM ISSUE I, PROJECT P WHERE P.P_ID=I.P_ID AND I.I_ID='!I_ID!'";

	$qr_it_idr_select_issueusers = "SELECT DISTINCT U_ID_ASSIGNED FROM ISSUE WHERE I_ID IN (%s)";

	//
	// Event handlers queries
	//

	$qr_it_userIssueAssigned = "SELECT I.I_NUM, I.PW_ID, P.P_DESC FROM ISSUE I, PROJECT P, PROJECTWORK PW WHERE P.P_ID=I.P_ID AND (P.P_ENDDATE IS NULL OR P.P_ENDDATE > CURDATE()) AND (PW.PW_ENDDATE IS NULL OR PW.PW_ENDDATE > CURDATE()) AND PW.P_ID=I.P_ID AND PW.PW_ID=I.PW_ID AND (U_ID_ASSIGNED='!U_ID!')";

	$qr_it_userIssueSender = "SELECT I.I_NUM, I.PW_ID, P.P_DESC FROM ISSUE I, PROJECT P, PROJECTWORK PW WHERE P.P_ID=I.P_ID AND PW.P_ID=I.P_ID AND PW.PW_ID=I.PW_ID AND (P.P_ENDDATE IS NULL OR P.P_ENDDATE > CURDATE()) AND (PW.PW_ENDDATE IS NULL OR PW.PW_ENDDATE > CURDATE()) AND (U_ID_SENDER='!U_ID!')";

	$qr_it_userIssueLogAssigned = "SELECT I.I_STATUSCURRENT, I.PW_ID, P.P_DESC FROM ISSUETRANSITIONLOG ITL, PROJECT P, ISSUE I, PROJECTWORK PW WHERE (ITL.U_ID_ASSIGNED='!ASSIGNED!' OR ITL.U_ID_SENDER='!SENDER!') AND P.P_ID=I.P_ID AND I.I_ID=ITL.I_ID AND PW.P_ID=I.P_ID AND PW.PW_ID=I.PW_ID AND (P.P_ENDDATE IS NULL OR P.P_ENDDATE > CURDATE()) AND (PW.PW_ENDDATE IS NULL OR PW.PW_ENDDATE > CURDATE())";

	$qr_it_userTransitionAssigned = "SELECT ITS.ITS_STATUS, ITS.PW_ID, P.P_DESC FROM ISSUETRANSITIONSCHEMA ITS, PROJECT P, PROJECTWORK PW WHERE PW.P_ID=ITS.P_ID AND PW.PW_ID=ITS.PW_ID AND ITS.U_ID_ASSIGNED='!U_ID!' AND P.P_ID=ITS.P_ID AND (P.P_ENDDATE IS NULL OR P.P_ENDDATE > CURDATE()) AND (PW.PW_ENDDATE IS NULL OR PW.PW_ENDDATE > CURDATE())";

	$qr_it_select_maxITL_date = "SELECT ITL.ITL_DATETIME FROM ISSUETRANSITIONLOG ITL, ISSUE I WHERE I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!' AND ITL.I_ID=I.I_ID ORDER BY ITL.ITL_DATETIME DESC";

	$qr_it_delete_user_schema_dependences = "UPDATE ISSUETRANSITIONSCHEMA SET U_ID_ASSIGNED=NULL WHERE U_ID_ASSIGNED='!U_ID!'";

	$qr_it_delete_user_sender_assignments = "UPDATE ISSUE SET U_ID_SENDER=NULL WHERE U_ID_SENDER='!U_ID!'";

	$qr_it_delete_user_assignee_assignments = "UPDATE ISSUE SET U_ID_ASSIGNED=NULL WHERE U_ID_ASSIGNED='!U_ID!'";

	$qr_it_delete_user_log_assignments = "UPDATE ISSUETRANSITIONLOG SET U_ID_ASSIGNED=NULL WHERE U_ID_ASSIGNED='!U_ID!'";

	$qr_it_delete_user_log_sender_assignments = "UPDATE ISSUETRANSITIONLOG SET U_ID_SENDER=NULL WHERE U_ID_SENDER='!U_ID!'";

	$qr_it_delete_user_templateschema_dependences = "UPDATE ISSUETRANSITIONTEMPLATESCHEMA SET ITTS_ASSIGNED=NULL WHERE ITTS_ASSIGNED='!U_ID!'";

	$qr_it_work_issue_count = "SELECT COUNT(*) FROM ISSUE WHERE PW_ID='!PW_ID!' AND P_ID='!P_ID!'";

	$qr_it_work_assigned_issue_count = "SELECT COUNT(*) FROM ISSUE I WHERE PW_ID='!PW_ID!' AND P_ID='!P_ID!' AND U_ID_ASSIGNED IS NOT NULL";

	$qr_it_delete_work_transitions = "DELETE FROM ISSUETRANSITIONSCHEMA WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_assignmentIssueAssigned = "SELECT I.I_NUM, I.PW_ID, P.P_DESC FROM ISSUE I, PROJECT P WHERE P.P_ID=I.P_ID AND (U_ID_ASSIGNED='!U_ID!') AND I.P_ID='!P_ID!' AND I.PW_ID='!PW_ID!'";

	$qr_it_delete_asn_schema_dependences = "UPDATE ISSUETRANSITIONSCHEMA SET U_ID_ASSIGNED=NULL WHERE U_ID_ASSIGNED='!U_ID!' AND P_ID='!P_ID!' AND PW_ID='!PW_ID!'";

	$qr_it_select_proj_issue_count = "SELECT COUNT(*) FROM ISSUE WHERE P_ID='!P_ID!'";

	$qr_it_delete_user_filters = "DELETE FROM ISSUEFILTER WHERE U_ID='!U_ID!'";

	$qr_it_invalidIssueDates = "SELECT COUNT(*) FROM ISSUE WHERE P_ID='!P_ID!' AND PW_ID='!PW_ID!' AND I_STARTDATE<'!I_STARTDATE!'";
	
	$qr_it_copyDefaultTransitions = "INSERT INTO ISSUETRANSITIONSCHEMA 
				(P_ID, PW_ID, ITS_NUM, ITS_STATUS, ITS_ALLOW_EDIT, ITS_ALLOW_DELETE, ITS_ASSIGNMENTOPTION, U_ID_ASSIGNED , ITS_COLOR, ITS_ALLOW_DEST,ITS_DEFAULT_DEST) 
			 SELECT
				0,0,TS.ITS_NUM, TS.ITTS_STATUS, TS.ITTS_ALLOW_EDIT, TS.ITTS_ALLOW_DELETE, TS.ITTS_ASSIGNMENTOPTION, TS.ITTS_ASSIGNED, TS.ITTS_COLOR, ITTS_ALLOW_DEST,TS.ITTS_DEFAULT_DEST
			 FROM ISSUETRANSITIONTEMPLATESCHEMA TS LEFT JOIN ISSUETRANSITIONSCHEMA S ON (S.P_ID=0 AND S.PW_ID=0 AND TS.ITS_NUM=S.ITS_NUM) WHERE TS.ITT_ID=0 AND S.ITS_NUM IS NULL";
	
	global $qr_it_deleteProjectsIssues;
	$qr_it_deleteProjectsIssues = "DELETE FROM  ISSUE WHERE P_ID <>0 AND PW_ID<>0";
?>