<?php
	$queries = array(
		"UPDATE PIXLIST SET PF_ID = REPLACE (PF_ID, '.', '' )",
		"ALTER TABLE `PIXLIST` CHANGE `PF_ID` `PF_ID` INT( 255 ) NOT NULL DEFAULT '0' ",
		"UPDATE PIXFOLDER SET PF_ID = REPLACE (PF_ID, '.', '' )",
		"UPDATE U_ACCESSRIGHTS SET AR_OBJECT_ID = REPLACE (AR_OBJECT_ID, '.', '' ) WHERE AR_PATH = '/ROOT/PD/FOLDERS'",
		"UPDATE UG_ACCESSRIGHTS SET AR_OBJECT_ID = REPLACE (AR_OBJECT_ID, '.', '' ) WHERE AR_PATH = '/ROOT/PD/FOLDERS'",
		"UPDATE WG_PARAM JOIN WG_WIDGET ON WG_PARAM.WG_ID = WG_WIDGET.WG_ID SET WGP_VALUE = REPLACE( WGP_VALUE, '.', '' ) WHERE WGP_NAME = 'FOLDERS' AND WT_ID = 'PDList'",		
		"ALTER TABLE `PIXFOLDER` CHANGE `PF_STATUS` `PF_STATUS` INT( 11 ) DEFAULT '2'",
		"ALTER TABLE `PIXFOLDER` CHANGE `PF_ID` `PF_ID` INT( 255 ) NOT NULL DEFAULT '0'",
		"ALTER TABLE `PIXFOLDER` ADD `PF_DATESTR` VARCHAR( 20 ) NOT NULL",
		"ALTER TABLE `PIXFOLDER` ADD `PF_THUMB` INT NOT NULL ",
		"ALTER TABLE `PIXFOLDER` ADD `PF_IMAGE_COUNT` INT NOT NULL ",
		"ALTER TABLE `PIXFOLDER` ADD `PF_SORT` INT NOT NULL DEFAULT '0'",
		"ALTER TABLE `PIXFOLDER` ADD `PF_DESC` TEXT NOT NULL ",
		"ALTER TABLE `PIXFOLDER` ADD `C_ID` INT NOT NULL ",
		"CREATE TABLE `PIXCOMMENTS` (
		  `PC_ID` int(11) NOT NULL auto_increment,
		  `PC_OWNER_IMAGE` int(11) default '0',
		  `PC_OWNER_ALBUM` int(11) default NULL,
		  `PC_AUTHER` varchar(20) NOT NULL,
		  `PC_EMAIL` varchar(20) NOT NULL,
		  `PC_TEXT` text NOT NULL,
		  `PC_DATEADD` datetime NOT NULL,
		  `PC_TYPE` int(1) default '3',
		  PRIMARY KEY  (`PC_ID`)
		) ENGINE=MyISAM DEFAULT CHARSET=utf8",
		"ALTER TABLE `PIXLIST` ADD `PL_ROTATE` INT NOT NULL DEFAULT '1'",
		"ALTER TABLE `PIXLIST` ADD `PL_WIDTH` INT( 5 ) NOT NULL ",
		"ALTER TABLE `PIXLIST` ADD `PL_HEIGHT` INT( 5 ) NOT NULL ",
		"ALTER TABLE `PIXLIST` ADD `C_ID` INT NOT NULL ",
		"UPDATE `PIXFOLDER` SET PF_STATUS =2",
		
		"CREATE TEMPORARY TABLE TEMP_PIXLIST AS SELECT PF_ID, PL_SORT FROM PIXLIST",
		"UPDATE PIXLIST SET PL_SORT = (SELECT COUNT(*) FROM TEMP_PIXLIST P WHERE P.PF_ID = PIXLIST.PF_ID AND P.PL_SORT < PIXLIST.PL_SORT)",	
		"DROP TABLE TEMP_PIXLIST",
		
		"CREATE TABLE `PIXEXIF` (
			`PL_ID` INT( 11 ) NOT NULL ,
			`PE_WIDTH` INT( 5 ) NOT NULL ,
			`PE_HEIGHT` INT( 5 ) NOT NULL ,
			`PE_DATETIME` DATETIME NOT NULL ,
			`PE_FILENAME` VARCHAR( 40 ) NOT NULL ,
			`PE_FILESIZE` INT NOT NULL ,
			`PE_MAKE` VARCHAR( 100 ) NOT NULL ,
			`PE_MODEL` VARCHAR( 100 ) NOT NULL ,
			`PE_EXPOSURETIME` VARCHAR( 50 ) NOT NULL ,
			`PE_FNUMBER` VARCHAR( 50 ) NOT NULL ,
			`PE_ISOSPEEDRATINGS` VARCHAR( 50 ) NOT NULL ,
			`PE_FOCALLENGTH` VARCHAR( 50 ) NOT NULL
		)",
		"ALTER TABLE `PIXLIST` CHANGE `PL_ID` `PL_ID` INT( 11 ) NOT NULL AUTO_INCREMENT  ",
		"ALTER TABLE `PIXFOLDER` CHANGE `PF_ID` `PF_ID` INT( 255 ) NOT NULL AUTO_INCREMENT  ",
		"ALTER TABLE `PIXFOLDER` ADD `PF_LINK` VARCHAR( 100 ) NOT NULL ",
		"ALTER TABLE `PIXFOLDER` CHANGE `PF_ID_PARENT` `PF_ID_PARENT` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'ROOT'",
		"ALTER TABLE `PIXFOLDER` ADD `PF_SETTING` TEXT NOT NULL ",
		
		"DROP TABLE IF EXISTS PIXACCESS",
		"DROP TABLE IF EXISTS PIXGROUPACCESS",
		"DROP TABLE IF EXISTS SHARED_TEMPLATES",
		"INSERT INTO `USER_SETTINGS` VALUES ('', 'PD', 'GalleryName', 'My photos')",
		"INSERT INTO `USER_SETTINGS` VALUES ('', 'PD', 'SharpenUsaged', '1')",
		"UPDATE PIXLIST SET PL_DESC = REPLACE(REPLACE(PL_DESC, '\r', ''), '\n', '<br/>\n')",
	
    	"INSERT IGNORE U_ACCESSRIGHTS (AR_ID, AR_PATH, AR_OBJECT_ID, AR_VALUE) SELECT AR_ID, AR_PATH, 'MANAGE_ALBUM', 7 FROM U_ACCESSRIGHTS WHERE AR_PATH = '/ROOT/PD/FOLDERS' AND AR_OBJECT_ID = 'ROOT' AND AR_VALUE = 7",
    	"INSERT IGNORE UG_ACCESSRIGHTS (AR_ID, AR_PATH, AR_OBJECT_ID, AR_VALUE) SELECT AR_ID, AR_PATH, 'MANAGE_ALBUM', 7 FROM UG_ACCESSRIGHTS WHERE AR_PATH = '/ROOT/PD/FOLDERS' AND AR_OBJECT_ID = 'ROOT' AND AR_VALUE = 7",	
		"INSERT IGNORE U_ACCESSRIGHTS (AR_ID, AR_PATH, AR_OBJECT_ID, AR_VALUE) SELECT AR_ID, '/ROOT/PD/FUNCTIONS', 'MANAGE_COLLECTIONS', 1 FROM U_ACCESSRIGHTS WHERE AR_PATH = '/ROOT/PD/FOLDERS' AND AR_OBJECT_ID='ROOT' AND ( AR_VALUE=7 OR AR_VALUE=1)",
		"INSERT IGNORE UG_ACCESSRIGHTS (AR_ID, AR_PATH, AR_OBJECT_ID, AR_VALUE) SELECT AR_ID, '/ROOT/PD/FUNCTIONS', 'MANAGE_COLLECTIONS', 1 FROM UG_ACCESSRIGHTS WHERE AR_PATH = '/ROOT/PD/FOLDERS' AND AR_OBJECT_ID='ROOT' AND ( AR_VALUE=7 OR AR_VALUE=1)"
	);
	
	foreach ($queries as $query) {
		$res = mysql_query($query);
	}
	
	include dirname(__FILE__).'/../include/Model/PDAlbum.php';	
	$album_model = new PDAlbum();
	$album_model->repair(true);

?>